# -*- cmake -*-
include(Linking)
include(Prebuilt)

option(USE_OPENAL "Enable OpenAL" ON)
if (USE_OPENAL)
  if (USESYSTEMLIBS)
    pkg_check_modules(FREEALUT REQUIRED freealut)
    pkg_check_modules(OPENAL REQUIRED openal)
  else (USESYSTEMLIBS)
    use_prebuilt_binary(openal)
    if(WINDOWS)
      set(OPENAL_LIBRARIES OpenAL32)
    else()
      set(OPENAL_LIBRARIES openal)
    endif()
    set(OPENAL_INCLUDE_DIRS "${LIBS_PREBUILT_DIR}/include/")

    set(FREEALUT_LIBRARIES alut)
    set(OPENAL_INCLUDE_DIRS "${LIBS_PREBUILT_DIR}/include/")
  endif (USESYSTEMLIBS)
endif (USE_OPENAL)
