# -*- cmake -*-
#
# The option names this project no longer reads, each with its replacement.
# A retired name found in the cache or on the command line would otherwise be
# ignored without a word, and the build would quietly take the default.

include_guard()

set(
  _al_retired_options
  BUILD_VIEWER=AL_BUILD_VIEWER
  BUILD_APPEARANCE_UTIL=AL_BUILD_APPEARANCE_UTILITY
  BUILD_HEADLESS=
  AL_BUILD_HEADLESS=
  BUILD_DULLAHAN_EXAMPLE=AL_BUILD_DULLAHAN_EXAMPLE
  BUILD_EXAMPLE_PLUGIN=AL_BUILD_EXAMPLE_PLUGIN
  BUILD_CEF_PLUGIN=AL_BUILD_CEF_PLUGIN
  BUILD_VLC_PLUGIN=AL_BUILD_VLC_PLUGIN
  BUILD_GSTREAMER_PLUGIN=AL_BUILD_GSTREAMER_PLUGIN
  PACKAGE=AL_BUILD_PACKAGE
  LL_COMMON_LINK_SHARED=AL_BUILD_SHARED_LLCOMMON
  USE_NDOF=AL_USE_NDOF
  USE_LTO=AL_USE_LTO
  USE_OPENXR=AL_USE_OPENXR
  USE_PRECOMPILED_HEADERS=AL_USE_PRECOMPILED_HEADERS
  USE_FMODSTUDIO=AL_USE_FMODSTUDIO
  USE_FAUDIO=AL_USE_FAUDIO
  USE_OPENAL=AL_USE_OPENAL
  USE_KDU=AL_USE_KDU
  USE_DISCORD=AL_USE_DISCORD
  USE_SDL_WINDOW=AL_USE_SDL_WINDOW
  USE_NSSPELLCHECKER=AL_USE_NSSPELLCHECKER
  USE_WINSPELLCHECK=AL_USE_WINSPELLCHECK
  USE_BUGSPLAT=
  USE_SENTRY=AL_USE_SENTRY
  USE_TRACY=AL_USE_TRACY
  USE_TRACY_ON_DEMAND=AL_ENABLE_TRACY_ON_DEMAND
  USE_TRACY_LOCAL_ONLY=AL_ENABLE_TRACY_LOCAL_ONLY
  USE_TRACY_GPU=AL_ENABLE_TRACY_GPU
  USE_TRACY_GUI=AL_BUILD_TRACY_GUI
  USE_VELOPACK=AL_USE_VELOPACK
  USE_LINUX_VOLUME_CATCHER=AL_USE_LINUX_VOLUME_CATCHER
  AL_LOCAL_DIST_DIR=
  AL_ARTWORK_DIR=
  USE_SSE4_2=AL_ISA_TIER
  USE_AVX=AL_ISA_TIER
  USE_AVX2=AL_ISA_TIER
  USE_AVX512=AL_ISA_TIER
  ENABLE_ASAN=AL_SANITIZERS
  ENABLE_UBSAN=AL_SANITIZERS
  ENABLE_THREADSAN=AL_SANITIZERS
  VS_DISABLE_FATAL_WARNINGS=AL_ENABLE_WARNINGS_AS_ERRORS
  GCC_DISABLE_FATAL_WARNINGS=AL_ENABLE_WARNINGS_AS_ERRORS
  CLANG_DISABLE_FATAL_WARNINGS=AL_ENABLE_WARNINGS_AS_ERRORS
  AL_WARNINGS_AS_ERRORS=AL_ENABLE_WARNINGS_AS_ERRORS
  ENABLE_SIGNING=AL_ENABLE_SIGNING
  SIGNING_IDENTITY=AL_SIGNING_IDENTITY
  INSTALL_PROPRIETARY=AL_ENABLE_PROPRIETARY
  RELEASE_CRASH_REPORTING=AL_ENABLE_CRASH_REPORTING
  NON_RELEASE_CRASH_REPORTING=AL_ENABLE_CRASH_REPORTING
  DISABLE_RELEASE_DEBUG_LOGGING=AL_ENABLE_RELEASE_DEBUG_LOGGING
  DISABLE_WEBRTC=AL_USE_WEBRTC
  VIEWER_CHANNEL=AL_CHANNEL
  GRID=AL_GRID
  BUGSPLAT_DB=
  AL_BUGSPLAT_DATABASE=
  SENTRY_DSN=AL_SENTRY_DSN
  ROOT_PROJECT_NAME=AL_PROJECT_NAME
  VIEWER_BINARY_NAME=AL_VIEWER_BINARY_NAME
  LOCAL_DIST_DIR=
  ARTWORK_DIR=
  FMODSTUDIO_SDK_DIR=AL_FMODSTUDIO_SDK_DIR
  TEMPLATE_VERIFIER_OPTIONS=AL_TEMPLATE_VERIFIER_MODE
  AL_TEMPLATE_VERIFIER_OPTIONS=AL_TEMPLATE_VERIFIER_MODE
  TEMPLATE_VERIFIER_MASTER_URL=AL_TEMPLATE_VERIFIER_MASTER_URL
  LL_TESTS=AL_BUILD_TESTS
  LLCOREHTTP_TESTS=AL_BUILD_TESTS
  HAVOK=
  USE_NVAPI=
  OS_DRAG_DROP=
  VERSION_BUILD=
)

set(_al_retired_found)
foreach(entry IN LISTS _al_retired_options)
  string(REPLACE "=" ";" pair "${entry}")
  list(GET pair 0 old)
  if(DEFINED ${old} OR DEFINED CACHE{${old}})
    # "NAME=" splits to a trailing empty element, which counts.
    list(GET pair 1 new)
    if(new)
      list(APPEND _al_retired_found "  ${old} -> ${new}")
    else()
      list(APPEND _al_retired_found "  ${old} -> (removed)")
    endif()
  endif()
endforeach()

if(_al_retired_found)
  list(JOIN _al_retired_found "\n" _al_retired_text)
  message(
    WARNING
    "Retired option names were found in the cache or on the command line and are ignored:\n${_al_retired_text}\nSet the replacement, and clear the old entry with -U<name> or by editing CMakeCache.txt."
  )
endif()

unset(_al_retired_options)
unset(_al_retired_found)
unset(_al_retired_text)
