#!/usr/bin/env python3
"""Writes indra/alscript/allsltraits.inc from lsl_definitions.yaml.

The optimizer folds a call to a library function only when the definitions
say the function has no side effects, and refuses to drop a call whose
result is unused when they say the result is the point. Those flags live
in lsl_definitions.yaml, which the lsl-definitions port ships; this reads
them without a YAML parser, since the file is regular, and writes a table
the library compiles in.

The LSL to SLua assistant reads the same table for what SLua makes of each
function: whether SLua's `ll` counts an index from one where LSL counts from
nought (an argument or the result with index-semantics), answers a boolean
where LSL answers 1 or 0 (a result with bool-semantics), or lacks it, leaving
it to `llcompat` alone (slua-removed); and what SLua would have used in its
stead (slua-deprecated's `use`). Run it whenever the definitions change:

    python3 scripts/content_tools/generate_lsl_traits.py \
        build-<OS>-<preset>/vcpkg_installed/<triplet>/share/lsl-definitions/lsl_definitions/lsl_definitions.yaml
"""

import re
import sys
from pathlib import Path

# Functions whose answer is their arguments' alone, which the definitions
# do not mark pure: most say only that their result must be used, and
# llAcos, llAsin and llDumpList2String say nothing. Marked pure here, so
# that the optimizer may fold them where it knows how and the inliner may
# read them at another time. A function that reads the world, the clock
# or a random source is not one of these.
DETERMINISTIC = {
    "llAcos",
    "llAsin",
    "llComputeHash",
    "llDumpList2String",
    "llHMAC",
    "llHash",
    "llLinear2sRGB",
    "llList2ListSlice",
    "llList2ListStrided",
    "llListFindList",
    "llListFindListNext",
    "llListFindStrided",
    "llListSort",
    "llListSortStrided",
    "llListStatistics",
    "llMD5String",
    "llRound",
    "llSHA1String",
    "llSHA256String",
    "llVerifyRSA",
    "llsRGB2Linear",
}


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    source = Path(argv[1])
    out = Path(__file__).resolve().parents[2] / "indra" / "alscript" / "allsltraits.inc"
    functions = {}
    name = None
    in_functions = False
    for line in source.read_text(encoding="utf-8").split("\n"):
        if re.match(r"^functions:\s*$", line):
            in_functions = True
            continue
        if in_functions and re.match(r"^[A-Za-z]", line):
            in_functions = False
        if not in_functions:
            continue
        m = re.match(r"^  ([A-Za-z_][A-Za-z0-9_]*):\s*$", line)
        if m:
            name = m.group(1)
            functions[name] = {"pure": False, "must-use": False, "native": False, "index": False, "bool": False, "removed": False, "use": None}
            in_deprecated = False
            continue
        if name is None:
            continue
        m = re.match(r"^    (pure|must-use|native): (true|false)\s*$", line)
        if m:
            functions[name][m.group(1)] = m.group(2) == "true"
        # An index counted from nought, in the result (four spaces in) or an
        # argument (eight); a result that is a boolean as 1 or 0.
        if re.match(r"^(    |        )index-semantics: true\s*$", line):
            functions[name]["index"] = True
        if re.match(r"^    bool-semantics: true\s*$", line):
            functions[name]["bool"] = True
        if re.match(r"^    slua-removed: true\s*$", line):
            functions[name]["removed"] = True
        if re.match(r"^    slua-deprecated:", line):
            in_deprecated = True
            continue
        if in_deprecated:
            m = re.match(r"^      use: (.*?)\s*$", line)
            if m:
                functions[name]["use"] = m.group(1).strip("'\"")
            elif not line.startswith("      "):
                in_deprecated = False
    if not functions:
        print("no functions found in " + str(source))
        return 1
    for fn in DETERMINISTIC:
        if fn not in functions:
            print("not in the definitions: " + fn)
            return 1
        functions[fn]["pure"] = True
    lines = [
        "// Generated by scripts/content_tools/generate_lsl_traits.py from",
        "// lsl_definitions.yaml; do not edit. One row per library function:",
        "// its name, whether it has no side effects, whether its result must",
        "// be used, whether it needs a native implementation off LSO; what",
        "// SLua makes of it (ALLSLTraits::Slua); and what SLua would use.",
        "// clang-format off",
    ]
    for fn in sorted(functions):
        t = functions[fn]
        slua = []
        if t["index"]:
            slua.append("SluaIndex")
        if t["bool"]:
            slua.append("SluaBool")
        if t["removed"]:
            slua.append("SluaRemoved")
        use = '"%s"' % t["use"].replace('\\', '\\\\').replace('"', '\\"') if t["use"] else "nullptr"
        lines.append(
            '{ "%s", %s, %s, %s, %s, %s },'
            % (
                fn,
                "true" if t["pure"] else "false",
                "true" if t["must-use"] else "false",
                "true" if t["native"] else "false",
                " | ".join(slua) if slua else "0",
                use,
            )
        )
    lines.append("// clang-format on")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    pure = sum(1 for t in functions.values() if t["pure"])
    print("%d functions, %d pure -> %s" % (len(functions), pure, out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
