#!/usr/bin/env python3
"""Writes indra/alscript/allsltraits.inc from lsl_definitions.yaml.

The optimizer folds a call to a library function only when the definitions
say the function has no side effects, and refuses to drop a call whose
result is unused when they say the result is the point. Those flags live
in lsl_definitions.yaml, which the lsl-definitions port ships; this reads
them without a YAML parser, since the file is regular, and writes a table
the library compiles in. Run it whenever the definitions change:

    python3 scripts/content_tools/generate_lsl_traits.py \
        build-<OS>-<preset>/vcpkg_installed/<triplet>/share/lsl-definitions/lsl_definitions/lsl_definitions.yaml
"""

import re
import sys
from pathlib import Path


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    source = Path(argv[1])
    out = Path(__file__).resolve().parents[2] / "indra" / "alscript" / "allsltraits.inc"
    functions = {}
    name = None
    in_functions = False
    for line in source.read_text(encoding="utf-8").split("\n"):
        if re.match(r"^functions:\s*$", line):
            in_functions = True
            continue
        if in_functions and re.match(r"^[A-Za-z]", line):
            in_functions = False
        if not in_functions:
            continue
        m = re.match(r"^  ([A-Za-z_][A-Za-z0-9_]*):\s*$", line)
        if m:
            name = m.group(1)
            functions[name] = {"pure": False, "must-use": False, "native": False}
            continue
        if name is None:
            continue
        m = re.match(r"^    (pure|must-use|native): (true|false)\s*$", line)
        if m:
            functions[name][m.group(1)] = m.group(2) == "true"
    if not functions:
        print("no functions found in " + str(source))
        return 1
    lines = [
        "// Generated by scripts/content_tools/generate_lsl_traits.py from",
        "// lsl_definitions.yaml; do not edit. One row per library function:",
        "// its name, whether it has no side effects, whether its result must",
        "// be used, and whether it needs a native implementation off LSO.",
        "// clang-format off",
    ]
    for fn in sorted(functions):
        t = functions[fn]
        lines.append(
            '{ "%s", %s, %s, %s },'
            % (fn, "true" if t["pure"] else "false", "true" if t["must-use"] else "false", "true" if t["native"] else "false")
        )
    lines.append("// clang-format on")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    pure = sum(1 for t in functions.values() if t["pure"])
    print("%d functions, %d pure -> %s" % (len(functions), pure, out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
