# -*- cmake -*-

add_library(llmessage STATIC)

target_sources(
  llmessage
  PRIVATE
    alnetimpairment.cpp
    llassetstorage.cpp
    llavatarname.cpp
    llavatarnamecache.cpp
    llbuffer.cpp
    llbufferstream.cpp
    llcachename.cpp
    llchainio.cpp
    llcircuit.cpp
    llclassifiedflags.cpp
    llcoproceduremanager.cpp
    llcorehttputil.cpp
    lldatapacker.cpp
    lldispatcher.cpp
    llexperiencecache.cpp
    llgenericstreamingmessage.cpp
    llhost.cpp
    llhttpnode.cpp
    llhttpsdhandler.cpp
    llinstantmessage.cpp
    lliobuffer.cpp
    lliopipe.cpp
    lliosocket.cpp
    llioutil.cpp
    llmessagebuilder.cpp
    llmessageconfig.cpp
    llmessagelog.cpp
    llmessagereader.cpp
    llmessagetemplate.cpp
    llmessagetemplateparser.cpp
    llmessagethrottle.cpp
    llnamevalue.cpp
    llpacketack.cpp
    llpacketbuffer.cpp
    llpacketring.cpp
    llpartdata.cpp
    llproxy.cpp
    llpumpio.cpp
    llsdappservices.cpp
    llsdhttpserver.cpp
    llsdmessagebuilder.cpp
    llsdmessagereader.cpp
    llstoredmessage.cpp
    lltemplatemessagebuilder.cpp
    lltemplatemessagedispatcher.cpp
    lltemplatemessagereader.cpp
    llthrottle.cpp
    lltransfermanager.cpp
    lltransfersourceasset.cpp
    lltransfersourcefile.cpp
    lltransfertargetfile.cpp
    lltransfertargetvfile.cpp
    lltrustedmessageservice.cpp
    llxfer.cpp
    llxfer_file.cpp
    llxfermanager.cpp
    llxfer_mem.cpp
    llxfer_vfile.cpp
    llxorcipher.cpp
    machine.cpp
    message.cpp
    message_prehash.cpp
    message_string_table.cpp
    net.cpp
    patch_code.cpp
    patch_dct.cpp
    patch_idct.cpp
    sound_ids.cpp
)

target_sources(
  llmessage
  PUBLIC
    FILE_SET HEADERS
      FILES
        alnetimpairment.h
        llassetstorage.h
        llavatarname.h
        llavatarnamecache.h
        llbuffer.h
        llbufferstream.h
        llcachename.h
        llchainio.h
        llcipher.h
        llcircuit.h
        llclassifiedflags.h
        llcoproceduremanager.h
        llcorehttputil.h
        lldatapacker.h
        lldbstrings.h
        lldispatcher.h
        lleventflags.h
        llexperiencecache.h
        llextendedstatus.h
        llfollowcamparams.h
        llgenericstreamingmessage.h
        llhost.h
        llhttpnode.h
        llhttpnodeadapter.h
        llhttpsdhandler.h
        llinstantmessage.h
        llinvite.h
        lliobuffer.h
        lliopipe.h
        lliosocket.h
        llioutil.h
        llloginflags.h
        llmessagebuilder.h
        llmessageconfig.h
        llmessagelog.h
        llmessagereader.h
        llmessagetemplate.h
        llmessagetemplateparser.h
        llmessagethrottle.h
        llmsgvariabletype.h
        llnamevalue.h
        llpacketack.h
        llpacketbuffer.h
        llpacketring.h
        llpartdata.h
        llpumpio.h
        llproxy.h
        llqueryflags.h
        llregionflags.h
        llregionhandle.h
        llsdappservices.h
        llsdhttpserver.h
        llsdmessagebuilder.h
        llsdmessagereader.h
        llstoredmessage.h
        lltaskname.h
        llteleportflags.h
        lltemplatemessagebuilder.h
        lltemplatemessagedispatcher.h
        lltemplatemessagereader.h
        llthrottle.h
        lltransfermanager.h
        lltransfersourceasset.h
        lltransfersourcefile.h
        lltransfertargetfile.h
        lltransfertargetvfile.h
        lltrustedmessageservice.h
        llvehicleparams.h
        llxfer.h
        llxfermanager.h
        llxfer_file.h
        llxfer_mem.h
        llxfer_vfile.h
        llxorcipher.h
        llzerocode.h
        machine.h
        mean_collision_data.h
        message.h
        message_prehash.h
        net.h
        patch_code.h
        patch_dct.h
        sound_ids.h
)

target_link_libraries(llmessage PRIVATE al::flags PUBLIC llcommon llfilesystem llmath llcorehttp)
target_precompile_headers(llmessage REUSE_FROM llprecompiled)

# tests
if(AL_BUILD_TESTS)
  foreach(test llcoproceduremanager llnamevalue lltrustedmessageservice lltemplatemessagedispatcher)
    al_add_test(${test} UNIT PROJECT llmessage LIBRARIES llmath llcorehttp)
  endforeach()

  set(
    test_libs
    llfilesystem
    llmath
    llcorehttp
    llmessage
    llcommon
  )
  al_add_test(io PROJECT llmessage SOURCES tests/llpipeutil.cpp LIBRARIES ${test_libs})
  foreach(
    test
    alnetimpairment
    llavatarnamecache
    llbuffer
    lldatapacker
    llhost
    llhttpnode
    llsdmessagebuilder
    llsdmessagereader
    llmessageconfig
    llmessagetemplateparser
    llpartdata
    lltemplatemessagebuilder
    llxfer_file
    llxorcipher
    llzerocode
    message
  )
    al_add_test(${test} PROJECT llmessage LIBRARIES ${test_libs})
  endforeach()
endif()
