name: Bug report
description: Viewer bug report
title: "[Bug]: "
labels: [bug, triage]
body:
- type: markdown
  attributes:
    value: |
      - Write a descriptive bug title above.
      - Search [open](https://github.com/AlchemyViewer/Alchemy/issues?q=is%3Aopen+label%3Abug+is%3Aissue) bugs to ensure that the issue has not already been identified.

- type: textarea
  attributes:
    label: Environment
    description: "Please copy the info from the viewer's 'About Alchemy' window and paste it here:"
    placeholder: ex. Alchemy Test 7.1.3.240191747 (64bit) ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: Explain the problem.
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction steps
    description: Steps to reproduce this bug
    placeholder: |
      1. First step
      2. Second step
      Expected: ...
      Actual: ...
  validations:
    required: true
