/**
 * @file alfloaterlightbox.cpp
 * @brief Lightbox post-processing control floater
 *
 * Copyright (C) Rye Mutt <rye@alchemyviewer.org>
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "llviewerprecompiledheaders.h"
#include "alfloaterlightbox.h"

#include "alcolorpicker.h"
#include "aldockpanel.h"
#include "alemptystate.h"
#include "alhistorylist.h"
#include "alpopover.h"
#include "alquickopen.h"
#include "alsettingrow.h"
#include "llaccordionctrl.h"
#include "llaccordionctrltab.h"
#include "llbutton.h"
#include "llcolorswatch.h"
#include "llcombobox.h"
#include "lleditmenuhandler.h"
#include "llfocusmgr.h"
#include "lltextbox.h"
#include "llfloaterreg.h"
#include "alcurveeditorctrl.h"
#include "alcurvemodel.h"
#include "altoolscenepicker.h"
#include "alwhitebalancesolver.h"
#include "llagent.h"
#include "llenvironment.h"
#include "llfile.h"
#include "llnotificationsutil.h"
#include "llpanel.h"
#include "llpresetsmanager.h"
#include "llsdutil.h"
#include "llsettingsvo.h"
#include "llsliderctrl.h"
#include "llspinctrl.h"
#include "lltabcontainer.h"
#include "lltimer.h"
#include "lltoolmgr.h"
#include "llviewercontrol.h"
#include "pipeline.h"
#include "rlvactions.h"

#include <algorithm>
#include <map>
#include <set>
#include <utility>

namespace
{
/// Everything recorded while this lives becomes a single undo step, called
/// @a label in the history list.
struct ScopedHistoryGroup
{
    explicit ScopedHistoryGroup(ALGradeHistory& history, const std::string& label = std::string())
    :   mHistory(history)
    {
        mHistory.beginGroup(label);
    }
    ~ScopedHistoryGroup() { mHistory.endGroup(); }
    ScopedHistoryGroup(const ScopedHistoryGroup&) = delete;
    ScopedHistoryGroup& operator=(const ScopedHistoryGroup&) = delete;

    ALGradeHistory& mHistory;
};

/// Holds a flag true for a scope. Never nested here -- if it ever is, this
/// needs to be a counter rather than a bool.
struct ScopedTrue
{
    explicit ScopedTrue(bool& flag) : mFlag(flag) { mFlag = true; }
    ~ScopedTrue() { mFlag = false; }
    ScopedTrue(const ScopedTrue&) = delete;
    ScopedTrue& operator=(const ScopedTrue&) = delete;

    bool& mFlag;
};

/// How long a caption stays lit after going to its setting: long enough to
/// find on a busy page, short enough not to be mistaken for a state.
constexpr F32 LIT_CAPTION_SECONDS = 2.5f;

/// A popover the Lightbox opens. The same placing and the same three ways out
/// as any other, plus the floater's own shortcuts while it has the keyboard:
/// the popover is a window of its own, so a key pressed in it never climbs
/// to the Lightbox, and Ctrl keys would go to the menu bar instead.
class ALLightboxPopover final : public ALPopover
{
public:
    using KeyHook = std::function<bool(KEY, MASK)>;

    ALLightboxPopover(const LLFloater::Params& p, KeyHook hook)
    :   ALPopover(p),
        mKeyHook(std::move(hook))
    {
    }

    /// Only with a hook to offer them to; otherwise the menu bar may have
    /// every Ctrl key as usual.
    bool hasAccelerators() const override { return (bool)mKeyHook; }

    bool handleKeyHere(KEY key, MASK mask) override
    {
        if (mKeyHook && mKeyHook(key, mask))
        {
            return true;
        }
        return ALPopover::handleKeyHere(key, mask);
    }

private:
    KeyHook mKeyHook;
};

/// The inline picker for a colour row: XUI Studio's hue ring, shade square and
/// channel tracks, under the row's name, with a way on to the viewer's full
/// picker for typed numbers and the eyedropper.
///
/// The picker is a child of the popover itself and not of a panel inside it,
/// and that is load-bearing: a panel takes Escape for itself and drops the
/// keyboard, which closes the popover as *settled*, and Escape here has to
/// mean "put the colour back".
class ALLightboxColorPopover final : public ALPopover
{
public:
    static constexpr S32 WIDTH = 300;
    static constexpr S32 PICKER_HEIGHT = 196;
    static constexpr S32 BUTTON_HEIGHT = 20;
    static constexpr S32 BUTTON_WIDTH = 110;
    static constexpr S32 GAP = 4;

    /// Laid out under the title, which is drawn across the top of the rect.
    static S32 heightFor(S32 header) { return header + GAP + PICKER_HEIGHT + GAP + BUTTON_HEIGHT + GAP; }

    ALLightboxColorPopover(const LLFloater::Params& p, const LLColor4& start,
                           std::function<void(const LLColor4&)> on_change,
                           std::function<void()> on_full_picker,
                           const std::string& full_picker_label, const std::string& full_picker_tooltip)
    :   ALPopover(p)
    {
        const S32 width = getRect().getWidth();
        const S32 top = getRect().getHeight() - getHeaderHeight();

        ALColorPicker::Params pp(LLUICtrlFactory::getDefaultParams<ALColorPicker>());
        pp.name = "picker";
        pp.rect = LLRect(GAP, top - GAP, width - GAP, top - GAP - PICKER_HEIGHT);
        pp.follows.flags = FOLLOWS_ALL;
        // Every colour row here is a Color3 setting: an alpha track would be a
        // control that does nothing.
        pp.show_alpha = false;
        ALColorPicker* picker = LLUICtrlFactory::create<ALColorPicker>(pp);
        picker->setColor(start);
        // Its value is text, "r, g, b, a"; the colour is what is wanted.
        picker->setCommitCallback([picker, on_change](LLUICtrl*, const LLSD&)
        {
            if (on_change)
            {
                on_change(picker->color());
            }
        });
        addChild(picker);

        LLButton::Params bp(LLUICtrlFactory::getDefaultParams<LLButton>());
        bp.name = "full_picker";
        bp.label = full_picker_label;
        bp.tool_tip = full_picker_tooltip;
        bp.rect = LLRect(width - GAP - BUTTON_WIDTH, GAP + BUTTON_HEIGHT, width - GAP, GAP);
        bp.follows.flags = FOLLOWS_RIGHT | FOLLOWS_BOTTOM;
        LLButton* full = LLUICtrlFactory::create<LLButton>(bp);
        full->setCommitCallback([on_full_picker](LLUICtrl*, const LLSD&)
        {
            if (on_full_picker)
            {
                on_full_picker();
            }
        });
        addChild(full);
    }
};
} // namespace

ALFloaterLightBox::ALFloaterLightBox(const LLSD& key)
:   LLFloater(key)
{
    mCommitCallbackRegistrar.add("LightBox.ResetControlDefault", std::bind(&ALFloaterLightBox::onClickResetControlDefault, this, std::placeholders::_2));
    mCommitCallbackRegistrar.add("LightBox.ResetSection", std::bind(&ALFloaterLightBox::onClickResetSection, this, std::placeholders::_2));
    mCommitCallbackRegistrar.add("LightBox.ToggleSection", std::bind(&ALFloaterLightBox::onToggleSection, this, std::placeholders::_1, std::placeholders::_2));
    mCommitCallbackRegistrar.add("LightBox.ReferenceGrab", std::bind(&ALFloaterLightBox::onClickReferenceGrab, this));
    mCommitCallbackRegistrar.add("LightBox.ReferenceClear", std::bind(&ALFloaterLightBox::onClickReferenceClear, this));
    mCommitCallbackRegistrar.add("LightBox.ToggleDayFreeze", std::bind(&ALFloaterLightBox::onToggleDayFreeze, this, std::placeholders::_1));
    mCommitCallbackRegistrar.add("LightBox.CommitDayTime", std::bind(&ALFloaterLightBox::onCommitDayTime, this, std::placeholders::_1));
    mCommitCallbackRegistrar.add("LightBox.DayPreset", std::bind(&ALFloaterLightBox::onClickDayPreset, this, std::placeholders::_2));
    mCommitCallbackRegistrar.add("LightBox.ToggleCloudScroll", std::bind(&ALFloaterLightBox::onToggleCloudScroll, this, std::placeholders::_1));
    mCommitCallbackRegistrar.add("LightBox.RestoreEnvironment", std::bind(&ALFloaterLightBox::onClickRestoreEnvironment, this));
    // Lambdas rather than bind: applyHistory answers whether it did anything,
    // and a commit callback returns nothing, so say plainly that the answer is
    // not wanted here. The buttons are greyed when there is nothing to do.
    mCommitCallbackRegistrar.add("LightBox.Undo", [this](LLUICtrl*, const LLSD&) { applyHistory(false); });
    mCommitCallbackRegistrar.add("LightBox.Redo", [this](LLUICtrl*, const LLSD&) { applyHistory(true); });
    mCommitCallbackRegistrar.add("LightBox.CommitVec3", std::bind(&ALFloaterLightBox::onCommitVec3, this, std::placeholders::_1));
    mCommitCallbackRegistrar.add("LightBox.CommitToneCurve", std::bind(&ALFloaterLightBox::onCommitToneCurve, this));
    mCommitCallbackRegistrar.add("LightBox.RefreshToneCurve", std::bind(&ALFloaterLightBox::refreshToneCurve, this));
    mCommitCallbackRegistrar.add("LightBox.ResetToneCurveChannel", std::bind(&ALFloaterLightBox::onClickResetToneCurveChannel, this));
    mCommitCallbackRegistrar.add("LightBox.ToneCurvePreset", std::bind(&ALFloaterLightBox::onToneCurvePreset, this, std::placeholders::_2));
    mCommitCallbackRegistrar.add("LightBox.CommitSplitToneGraph", std::bind(&ALFloaterLightBox::onCommitSplitToneGraph, this));
    mCommitCallbackRegistrar.add("LightBox.PickWhiteBalance", std::bind(&ALFloaterLightBox::onClickWhiteBalancePicker, this));
    mCommitCallbackRegistrar.add("LightBox.OpenLUTFolder", std::bind(&ALFloaterLightBox::onClickOpenLUTFolder, this));
    mCommitCallbackRegistrar.add("LightBox.LensDirtSliderDown", std::bind(&ALFloaterLightBox::onLensDirtSliderHeld, this, true));
    mCommitCallbackRegistrar.add("LightBox.LensDirtSliderUp", std::bind(&ALFloaterLightBox::onLensDirtSliderHeld, this, false));
    mCommitCallbackRegistrar.add("LightBox.LookSelected", std::bind(&ALFloaterLightBox::onLookSelected, this));
    mCommitCallbackRegistrar.add("LightBox.LookSave", std::bind(&ALFloaterLightBox::onClickLookSave, this));
    mCommitCallbackRegistrar.add("LightBox.LookSaveAs", std::bind(&ALFloaterLightBox::onClickLookSaveAs, this));
    mCommitCallbackRegistrar.add("LightBox.LookDelete", std::bind(&ALFloaterLightBox::onClickLookDelete, this));
    mCommitCallbackRegistrar.add("LightBox.LookRevert", std::bind(&ALFloaterLightBox::onClickLookRevert, this));
    mCommitCallbackRegistrar.add("LightBox.Find", std::bind(&ALFloaterLightBox::openFind, this));
    mCommitCallbackRegistrar.add("LightBox.History", std::bind(&ALFloaterLightBox::openHistory, this));
    mCommitCallbackRegistrar.add("LightBox.PopOut", std::bind(&ALFloaterLightBox::togglePane, this));
}

ALFloaterLightBox::~ALFloaterLightBox()
{
    // onClose has settled any popover already; this is for a floater that
    // dies without closing. die() and not a close, so nothing it holds calls
    // back into a floater half torn down.
    if (ALPopover* popover = mPopover.get())
    {
        popover->die();
    }
    // onClose has put every page back; this is for a floater that dies
    // without closing, which would otherwise leave a page in a window of its
    // own wired to callbacks on a floater that is gone. By handle, because a
    // pane still out belongs to its window, and that window may be gone first.
    dockPanes();

    // The handle in the pick callback already makes a late sample harmless, but
    // an armed picker outliving its floater would leave the user holding an
    // eyedropper cursor that has nothing left to tell. Put the previous tool
    // back instead.
    if (LLToolMgr::instanceExists() &&
        LLToolMgr::getInstance()->getCurrentTool() == ALToolScenePicker::getInstance())
    {
        LLToolMgr::getInstance()->clearTransientTool();
    }

    // The bypass mask lives in the pipeline and the checkboxes that drive it
    // live here, so closing the floater with one ticked would leave a section
    // permanently suppressed with nothing left on screen to say so, and no
    // setting to inspect either. The comparison ends when the tool does.
    LLPipeline::sGradeBypassMask = 0;

    // Same rule for the reference still, with a second reason: it is a
    // full-resolution target, so leaving one behind holds real memory for a
    // comparison nobody can see or turn off any more.
    gSavedSettings.setS32("RenderReferenceWipeMode", 0);
    gPipeline.clearReferenceStill();
}

bool ALFloaterLightBox::postBuild()
{
    mTabs = getChild<LLTabContainer>("lightbox_tabs");
    for (S32 i = 0; i < mTabs->getTabCount(); ++i)
    {
        if (LLPanel* page = mTabs->getPanelByIndex(i))
        {
            mTabPages.push_back(page);
            // Each page's tool_tip is written for its tab button, and
            // addTabPanel has already copied it there. Left on the page too it
            // is worse than useless: LLView::handleToolTip offers a parent's
            // tooltip before its children's, so it would pop up over every
            // caption, gap and header on the page that has none of its own.
            page->setToolTip(LLStringUtil::null);
        }
    }
    // Normally clear here -- a new Lightbox opens with every section switched
    // on -- but the mask belongs to the pipeline, so read it rather than
    // assume it.
    refreshBypassBadge();

    // Every section and setting, while they are all still where the XUI put
    // them. See mDirectory.
    mDirectory.build(mTabPages);
    mTopBar = findChild<LLPanel>("lightbox_topbar");

    populateLUTCombo();

    // Khronos Neutral (0), ACES (1) and GT (5) take no parameters, so their
    // selection leaves every one of these rows greyed.
    static const std::pair<const char*, S32> tonemapper_rows[] = {
        { "tone_aces_white", 2 },
        { "tone_reinhard_white", 3 },
        { "tone_filmic_white", 4 },
        { "tone_agx_contrast", 6 },
        { "tone_agx_white", 6 },
    };
    for (const auto& row : tonemapper_rows)
    {
        // Setting rows, which grey their own reset buttons along with them.
        mTonemapperRows.push_back({ row.second, findChild<LLUICtrl>(row.first) });
    }
    mTonemapConnection = gSavedSettings.getControl("AlchemyRenderTonemapType")->getSignal()->connect(
        [this](LLControlVariable*, const LLSD&, const LLSD&) { updateTonemapperRows(); });
    updateTonemapperRows();

    mLookSave = findChild<LLUICtrl>("look_save");
    mLookDelete = findChild<LLUICtrl>("look_delete");
    mLookRevert = findChild<LLUICtrl>("look_revert");
    mLooksCombo = getChild<LLComboBox>("looks_combo");
    mLooksListConnection = LLPresetsManager::instance().setPresetListChangeLooksCallback(
        std::bind(&ALFloaterLightBox::refreshLooksBar, this));
    mLooksActiveConnection = gSavedSettings.getControl("PresetLooksActive")->getSignal()->connect(
        [this](LLControlVariable*, const LLSD&, const LLSD&) { refreshLooksBar(); });
    refreshLooksBar();

    mUndoButton = findChild<LLUICtrl>("look_undo");
    mRedoButton = findChild<LLUICtrl>("look_redo");
    mHistoryButton = findChild<LLUICtrl>("look_history");
    mReferenceClear = findChild<LLUICtrl>("reference_clear");
    mReferenceMode = findChild<LLUICtrl>("reference_mode");
    mReferencePosition = findChild<LLUICtrl>("reference_position");

    mDayFreeze = findChild<LLUICtrl>("day_freeze");
    mDayTime = findChild<LLUICtrl>("day_time");
    mCloudScroll = findChild<LLUICtrl>("day_pause_clouds");
    mRestoreEnvironment = findChild<LLUICtrl>("day_restore_environment");
    mDayPresets = { findChild<LLUICtrl>("day_sunrise"), findChild<LLUICtrl>("day_noon"),
                    findChild<LLUICtrl>("day_sunset"), findChild<LLUICtrl>("day_midnight") };

    // Undo watches exactly the settings a Look carries. Sharing that list is
    // the point: a control worth saving is a control worth undoing, so a new
    // grading setting joins both at once instead of one and not the other.
    //
    // The signal hands over the old value as well as the new one, so there is
    // no shadow copy to keep in step -- and llcontrol only fires it when the
    // value really changed (setValue and resetToDefault both gate on
    // llsd_compare), so a commit that rewrites the same value cannot put a
    // do-nothing step on the stack.
    std::vector<std::string> looks_controls;
    LLPresetsManager::instance().getLooksControlNames(looks_controls);
    for (const std::string& setting : looks_controls)
    {
        LLControlVariable* controlp = gSavedSettings.getControl(setting);
        if (!controlp)
        {
            // LLPresetsManager already warns loudly about a whitelist name
            // that has stopped existing; no need to say it twice.
            continue;
        }
        mHistoryConnections.emplace_back(controlp->getSignal()->connect(
            [this, setting](LLControlVariable*, const LLSD& new_value, const LLSD& old_value)
            { onGradeSettingChanged(setting, old_value, new_value); }));
        mRecordedKeys.insert(setting);
    }

    LLHandle<ALFloaterLightBox> self = getDerivedHandle<ALFloaterLightBox>();
    for (const ALLightboxDirectory::Setting& setting : mDirectory.settings())
    {
        const std::string key = setting.mKey;

        // Colour rows pick inline. Only Color3 swatches: the inline picker has
        // no alpha, and a Color4 row would lose its fourth number to it.
        LLColorSwatchCtrl* swatch = ALViewType::as<LLColorSwatchCtrl>(setting.mCtrl);
        LLControlVariable* controlp = gSavedSettings.getControl(key);
        if (swatch && controlp && controlp->type() == TYPE_COL3)
        {
            swatch->setPickerOverride([self, key](LLColorSwatchCtrl* from)
            {
                ALFloaterLightBox* floater = self.get();
                return floater && floater->openColorPopover(from, key);
            });
        }

        // A setting row's reset comes through here, the same as a reset
        // button's: a named undo step of its own rather than a bare write
        // that folds into a drag just before it.
        if (ALSettingRow* row = ALViewType::as<ALSettingRow>(setting.mCtrl))
        {
            row->setResetHandler([self, key](ALSettingRow*)
            {
                if (ALFloaterLightBox* floater = self.get())
                {
                    floater->onClickResetControlDefault(LLSD(key));
                }
            });
        }
    }

    ALLightboxDirectory::collectVec3Controls(this, mVec3Rows);
    for (const auto& row : mVec3Rows)
    {
        const std::string& setting = row.first;
        LLControlVariable* controlp = gSavedSettings.getControl(setting);
        if (!controlp)
        {
            LL_WARNS() << "Vec3 row bound to unknown setting: " << setting << LL_ENDL;
            continue;
        }
        mVec3Connections.emplace_back(controlp->getSignal()->connect(
            [this, setting](LLControlVariable*, const LLSD&, const LLSD&) { refreshVec3Row(setting); }));
        refreshVec3Row(setting);
    }

    setupToneCurve();
    setupSplitToneGraph();

    fitSections();

    // Last, after everything above has found what it needs: from here a page
    // can be taken out of the floater, and nothing may look for a widget
    // through it again.
    mPopOutButton = findChild<LLButton>("lightbox_pop_out");
    for (size_t index = 0; index < mTabPages.size(); ++index)
    {
        LLPanel* page = mTabPages[index];
        LLStringUtil::format_map_t args;
        args["[TAB]"] = page->getLabel();

        Pane pane;
        if (ALDockPanel* dock = ALDockPanel::wrap(page, getString("pane_title", args)))
        {
            pane.mPane = dock->getHandle();
        }

        // What the page says while its pane is away: added after the wrap, so
        // it stays on the page when the page's contents go.
        ALEmptyState::Params ep(LLUICtrlFactory::getDefaultParams<ALEmptyState>());
        ep.name = page->getName() + "_away";
        ep.rect = page->getLocalRect();
        ep.follows.flags = FOLLOWS_ALL;
        ep.background_visible = false;
        ep.visible = false;
        pane.mEmpty = LLUICtrlFactory::create<ALEmptyState>(ep);
        page->addChild(pane.mEmpty);
        pane.mEmpty->say(getString("pane_away_headline", args), getString("pane_away_sentence", args),
                         getString("pane_put_back"));
        pane.mEmpty->onAction([self, index]()
        {
            if (ALFloaterLightBox* floater = self.get())
            {
                floater->dockPane(index);
            }
        });
        mPanes.push_back(pane);
    }
    restorePanes();

    return LLFloater::postBuild();
}

// Shared by the colour LUT and lens dirt pickers. Both enumerate a bundled
// directory and a user directory of the same name, list the bundled entries
// first and the user ones behind a separator, and select whatever the setting
// currently holds. Generalised rather than cloned: the two differ only in
// directory, accepted extensions, and which setting they write.
//
// `extensions` must list only what the corresponding loader can actually
// handle. Anything else in the directory -- a readme, a subfolder, a stray
// .bak -- would become a selectable entry that fails at apply time with
// nothing but a log line to say why. getExtension lowercases, so a .CUBE
// passes here the same way it does when the renderer resolves it.
void ALFloaterLightBox::populateAssetCombo(const std::string& combo_name,
                                           const std::string& dir_name,
                                           const std::vector<std::string>& extensions,
                                           const std::string& setting_name)
{
    LLComboBox* combo = getChild<LLComboBox>(combo_name);

    // Collected rather than added on the spot, so the caller can see whether
    // a directory contributed anything before committing to the separator.
    auto collect_from = [&extensions](const std::string& scan_dir)
    {
        std::vector<std::pair<std::string, std::string>> found; // stem, filename

        std::error_code ec;
        std::filesystem::path scan_path = fsyspath(scan_dir);
        if (!std::filesystem::is_directory(scan_path, ec) || ec)
        {
            return found;
        }

        // increment(ec), not ++: the throwing increment would carry a
        // transient filesystem error out through postBuild. On failure it
        // parks the iterator at end instead, which is why ec is looked at
        // again once the loop is done.
        std::filesystem::directory_iterator end;
        for (std::filesystem::directory_iterator entry(scan_path, ec); entry != end && !ec; entry.increment(ec))
        {
            std::error_code entry_ec;
            if (!entry->is_regular_file(entry_ec) || entry_ec)
            {
                continue;
            }
#if LL_WINDOWS
            std::string entry_stem = ll_convert_wide_to_string(entry->path().stem().native());
            std::string entry_filename = ll_convert_wide_to_string(entry->path().filename().native());
#else
            std::string entry_stem = entry->path().stem().native();
            std::string entry_filename = entry->path().filename().native();
#endif
            const std::string exten = gDirUtilp->getExtension(entry_filename);
            if (std::find(extensions.begin(), extensions.end(), exten) == extensions.end())
            {
                continue;
            }
            found.emplace_back(std::move(entry_stem), std::move(entry_filename));
        }
        if (ec)
        {
            LL_WARNS() << "Error reading asset directory " << scan_dir << ": " << ec.message() << LL_ENDL;
        }
        return found;
    };

    // Bundled entries first, then user entries behind a separator — the same order
    // the renderer resolves a name in, where the user dir wins.
    for (const auto& entry : collect_from(gDirUtilp->getExpandedFilename(LL_PATH_APP_SETTINGS, dir_name)))
    {
        combo->add(entry.first, entry.second);
    }

    const auto user_entries = collect_from(gDirUtilp->getExpandedFilename(LL_PATH_USER_SETTINGS, dir_name));
    if (!user_entries.empty())
    {
        combo->addSeparator();
        for (const auto& entry : user_entries)
        {
            combo->add(entry.first, entry.second);
        }
    }

    // Mandatory: the combo is allow_text_entry, so nothing else selects the
    // saved value when the floater opens.
    combo->selectByValue(gSavedSettings.getString(setting_name));
    combo->resetDirty();
}

void ALFloaterLightBox::populateLUTCombo()
{
    static const std::vector<std::string> LUT_EXTENSIONS = { "cube", "tga", "png", "jpg", "jpeg", "bmp", "webp" };
    populateAssetCombo("colorlut_combo", "colorlut", LUT_EXTENSIONS, "RenderColorGradeLUT");
}

// Parameterised by directory even though the colour LUT is once again the only
// caller: the lens dirt plate that shared it is generated now. Kept general
// because the shape is the shared part -- user folder, created on demand -- and
// collapsing it back to a constant only has to be undone for the next asset.
void ALFloaterLightBox::openUserAssetFolder(const std::string& dir_name)
{
    // The user's folder, not the bundled one: it is the half of the pair that
    // is theirs to put files in, and the one the renderer prefers when a name
    // exists in both. Nothing creates it until there is something to put in
    // it, which is exactly now -- and LLFile::mkdir is quiet about a
    // directory that already exists.
    const std::string dir = gDirUtilp->getExpandedFilename(LL_PATH_USER_SETTINGS, dir_name);
    LLFile::mkdir(dir);
    gDirUtilp->openDir(dir);
}

// The lens dirt plate is regenerated whenever one of its parameters changes,
// and at full resolution that is too expensive to do on every frame of a slider
// drag. Rather than guess when a drag has ended from a timer, say so: the
// renderer holds off while this is raised and rebuilds once on release.
//
// Only the generation sliders carry these. Strength and the two response
// controls are applied per frame at composite time and rebuild nothing, so
// holding them off would only make them feel broken.
void ALFloaterLightBox::onLensDirtSliderHeld(bool held)
{
    gPipeline.mLensDirtSliderHeld = held;
}

void ALFloaterLightBox::onClickOpenLUTFolder()
{
    openUserAssetFolder("colorlut");
}

void ALFloaterLightBox::onClickResetControlDefault(const LLSD& userdata)
{
    const std::string& control_name = userdata.asString();
    LLControlVariable* controlp = gSavedSettings.getControl(control_name);
    if (controlp)
    {
        // A group, though it is one control: it names the step, and a reset
        // straight after a drag of the same control is a second thing done
        // rather than the end of the drag, which it would otherwise coalesce
        // into.
        LLStringUtil::format_map_t args;
        args["[SETTING]"] = mDirectory.captionFor(control_name);
        ScopedHistoryGroup group(mHistory, getString("history_reset_setting", args));
        controlp->resetToDefault(true);
    }
}

void ALFloaterLightBox::onClickResetSection(const LLSD& userdata)
{
    const std::string& section = userdata.asString();
    if (section.empty())
    {
        return;
    }

    // From the directory, not by name: the section may be on a page that has
    // been taken out into a window of its own, out of reach of a search from
    // this floater.
    std::set<std::string> keys;
    const ALLightboxDirectory::Section* mainp = mDirectory.section(section);
    if (mainp)
    {
        ALLightboxDirectory::collectBoundKeys(mainp->mPanel, keys);
    }
    if (const ALLightboxDirectory::Section* advp = mDirectory.section(section + "_adv"))
    {
        ALLightboxDirectory::collectBoundKeys(advp->mPanel, keys);
    }

    // A section's own header can carry a bound checkbox -- Color Grading's
    // master switch does -- and that is part of the section however it is
    // drawn. It is not in the panel, so nothing above would find it. Walk the
    // control rather than reading it directly: LLCheckBoxCtrl hands
    // control_name down to its button, so the binding is on the child.
    if (mainp && mainp->mTab)
    {
        if (LLCheckBoxCtrl* checkp = mainp->mTab->getHeaderCheckBox())
        {
            ALLightboxDirectory::collectBoundKeys(checkp, keys);
        }
    }

    // One thing the user did, however many controls it moves: undoing a Reset
    // All eleven times would be absurd.
    LLStringUtil::format_map_t args;
    args["[SECTION]"] = mainp ? mainp->mTitle : section;
    ScopedHistoryGroup group(mHistory, getString("history_reset_section", args));
    for (const std::string& key : keys)
    {
        if (LLControlVariable* controlp = gSavedSettings.getControl(key))
        {
            controlp->resetToDefault(true);
        }
    }
}

void ALFloaterLightBox::onToggleSection(LLUICtrl* ctrl, const LLSD& userdata)
{
    // Section id to bit. The grouping matches Reset All's, which walks
    // sec_<id> and sec_<id>_adv together, so a section with a long tail in an
    // Advanced sibling is one switch and one idea of what a section is.
    static const std::map<std::string, U32> bypass_bits = {
        { "basic",     LLPipeline::GRADE_BYPASS_BASIC },
        { "primaries", LLPipeline::GRADE_BYPASS_PRIMARIES },
        { "split",     LLPipeline::GRADE_BYPASS_SPLIT },
        { "lut",       LLPipeline::GRADE_BYPASS_LUT },
        { "curve",     LLPipeline::GRADE_BYPASS_CURVE },
    };

    const auto found = bypass_bits.find(userdata.asString());
    if (!ctrl || found == bypass_bits.end())
    {
        return;
    }

    // Ticked is the section switched on, so the bit -- which suppresses --
    // is set when the box is clear.
    //
    // Nothing is written to gSavedSettings here, deliberately: every grading
    // control is on the Looks whitelist, so a comparison built out of one
    // would mark the active Look dirty and could then be saved mid-comparison.
    // That is also why the checkboxes have no control_name: they are worth
    // exactly one viewing session, and the floater is destroyed when it
    // closes, which is what puts them all back on.
    if (ctrl->getValue().asBoolean())
    {
        LLPipeline::sGradeBypassMask &= ~found->second;
    }
    else
    {
        LLPipeline::sGradeBypassMask |= found->second;
    }

    // The only writer of the mask, so the only place the badge can go stale.
    refreshBypassBadge();
}

void ALFloaterLightBox::refreshBypassBadge()
{
    if (!mTabs || mTabPages.empty())
    {
        return;
    }

    // Counted from the mask rather than from the checkboxes: the mask is what
    // the renderer obeys, and the badge is there to say what it is obeying.
    static constexpr U32 section_bits[] = {
        LLPipeline::GRADE_BYPASS_BASIC,
        LLPipeline::GRADE_BYPASS_PRIMARIES,
        LLPipeline::GRADE_BYPASS_SPLIT,
        LLPipeline::GRADE_BYPASS_LUT,
        LLPipeline::GRADE_BYPASS_CURVE,
    };
    S32 bypassed = 0;
    for (U32 bit : section_bits)
    {
        if (LLPipeline::sGradeBypassMask & bit)
        {
            ++bypassed;
        }
    }

    std::string label;
    if (bypassed > 0)
    {
        LLStringUtil::format_map_t args;
        args["[COUNT]"] = llformat("%d", bypassed);
        label = getString("bypass_badge", args);
    }
    // The Look tab is the first page; the grading sections all live on it.
    mTabs->setTabBadge(mTabPages.front(), label);
}

void ALFloaterLightBox::onClickReferenceGrab()
{
    // The grab is serviced on the next frame's blit, so what gets frozen is
    // what the user is looking at as they click, not a frame already gone.
    gPipeline.requestReferenceStill();

    // Switching the wipe on is the feedback that the grab happened: a Grab
    // button that visibly does nothing reads as broken, and a still nobody is
    // looking at has no reason to exist yet.
    if (gSavedSettings.getS32("RenderReferenceWipeMode") == 0)
    {
        gSavedSettings.setS32("RenderReferenceWipeMode", 1);
    }

    // The still does not exist until the frame renders, so the row cannot be
    // refreshed to its final state here; the draw loop picks it up.
    refreshReferenceRow();
}

void ALFloaterLightBox::onClickReferenceClear()
{
    gSavedSettings.setS32("RenderReferenceWipeMode", 0);
    gPipeline.clearReferenceStill();
    refreshReferenceRow();
}

void ALFloaterLightBox::refreshReferenceRow()
{
    // Whether a still exists is render state, not a setting, so nothing
    // signals its arrival -- a grab is only serviced when the frame renders,
    // and a resize drops the still without asking. Hence the poll from draw().
    const bool have_still = gPipeline.hasReferenceStill();
    const S32  mode = gSavedSettings.getS32("RenderReferenceWipeMode");

    // Only the wipe has a movable seam; side by side is always centred.
    const S32 state = (have_still ? 1 : 0) | ((have_still && mode == 1) ? 2 : 0);
    if (state == mReferenceRowState)
    {
        return;
    }
    mReferenceRowState = state;

    if (mReferenceClear)
    {
        mReferenceClear->setEnabled(have_still);
    }
    if (mReferenceMode)
    {
        mReferenceMode->setEnabled(have_still);
    }
    if (mReferencePosition)
    {
        mReferencePosition->setEnabled((state & 2) != 0);
    }
}

void ALFloaterLightBox::refreshHistoryButtons()
{
    // Polled for the same reason the reference row is: the stack moves on
    // every commit, on every undo, and on a Look being applied, and hanging a
    // refresh off each of those is more places to forget than this costs.
    const S32 state = (mHistory.canUndo() ? 1 : 0) | (mHistory.canRedo() ? 2 : 0);
    if (state == mHistoryButtonState)
    {
        return;
    }
    mHistoryButtonState = state;

    if (mUndoButton)
    {
        mUndoButton->setEnabled((state & 1) != 0);
    }
    if (mRedoButton)
    {
        mRedoButton->setEnabled((state & 2) != 0);
    }
}

void ALFloaterLightBox::draw()
{
    refreshReferenceRow();
    refreshHistoryButtons();
    refreshDayCycleRow();
    refreshPaneRow();

    if (LLView* lit = mLitCaption.get())
    {
        if (mLitTimer.getElapsedTimeF32() > LIT_CAPTION_SECONDS)
        {
            if (LLTextBox* box = ALViewType::as<LLTextBox>(lit))
            {
                box->setHighlighted(false);
            }
            mLitCaption.markDead();
        }
    }

    // The history list follows the stack while it is up: Ctrl+Z pressed in
    // it, a drag in the floater behind it, a Look applied from the bar.
    if (mHistoryList.get() && mHistory.revision() != mHistoryListRevision)
    {
        fillHistoryList();
    }

    LLFloater::draw();
}

void ALFloaterLightBox::onClose(bool app_quitting)
{
    closePopover(false);
    // Saved before they are put back, or every page would be remembered as
    // here. And put back even when the viewer is quitting: windows are closed
    // in no particular order then, and this is the last point at which both
    // this floater and every torn-off window are sure to still be whole.
    savePanes();
    dockPanes();
    LLFloater::onClose(app_quitting);
}

ALPopover* ALFloaterLightBox::showPopover(PopoverKind kind, LLView* anchor, LLPanel* content, PopoverKeyHook hook)
{
    if (!anchor || !content)
    {
        delete content;
        return nullptr;
    }

    // What ALPopover::show does, with the key hook added: no title, since
    // the content is laid out over the whole popover and a title bar would be
    // drawn under it.
    const LLRect wanted = content->getRect();
    ALLightboxPopover* popover = new ALLightboxPopover(
        ALPopover::paramsFor(wanted.getWidth(), wanted.getHeight()), std::move(hook));
    content->setOrigin(0, 0);
    content->setFollows(FOLLOWS_ALL);
    popover->addChild(content);

    adoptPopover(kind, popover, anchor);
    return popover;
}

void ALFloaterLightBox::adoptPopover(PopoverKind kind, ALPopover* popover, LLView* anchor)
{
    closePopover(true);

    mPopover = popover->getDerivedHandle<ALPopover>();
    mPopoverKind = kind;
    // Handles both ways: the popover is a top-level window and can outlive
    // this floater by a frame, and this floater can be closed under it.
    LLHandle<ALFloaterLightBox> self = getDerivedHandle<ALFloaterLightBox>();
    LLHandle<ALPopover> which = mPopover;
    popover->onClosed([self, which](bool escaped)
    {
        if (ALFloaterLightBox* floater = self.get())
        {
            floater->onPopoverClosed(which.get(), escaped);
        }
    });

    popover->openBeside(anchor);
}

void ALFloaterLightBox::closePopover(bool escape)
{
    if (ALPopover* popover = mPopover.get())
    {
        if (escape)
        {
            popover->escape();
        }
        else
        {
            popover->settle();
        }
    }
}

void ALFloaterLightBox::onPopoverClosed(const LLView* which, bool escaped)
{
    // One that was replaced before it finished closing has nothing to say
    // about the one up now.
    if (!which || which != mPopover.get())
    {
        return;
    }
    const PopoverKind kind = mPopoverKind;
    mPopover.markDead();
    mPopoverKind = PopoverKind::None;
    mHistoryList.markDead();

    if (kind == PopoverKind::Color)
    {
        endColorSession(escaped);
    }
}

bool ALFloaterLightBox::openColorPopover(LLColorSwatchCtrl* swatch, const std::string& key)
{
    LLControlVariable* control = gSavedSettings.getControl(key);
    if (!swatch || !control)
    {
        return false;
    }
    // Closed before the session below starts, so a colour popover already up
    // finishes its own session with its own setting.
    closePopover(true);

    // A Color3 arrives as three numbers, which LLColor4 reads as transparent.
    LLColor4 start(control->getValue());
    start.mV[VALPHA] = 1.f;
    mColorKey = key;
    mColorOriginal = control->getValue();

    LLHandle<ALFloaterLightBox> self = getDerivedHandle<ALFloaterLightBox>();
    LLHandle<LLView> swatch_handle = swatch->getHandle();
    const S32 header = LLFloater::getDefaultParams().header_height;
    ALLightboxColorPopover* popover = new ALLightboxColorPopover(
        ALPopover::paramsFor(ALLightboxColorPopover::WIDTH, ALLightboxColorPopover::heightFor(header),
                             mDirectory.captionFor(key)),
        start,
        [self](const LLColor4& color)
        {
            if (ALFloaterLightBox* floater = self.get())
            {
                floater->onColorPicked(color);
            }
        },
        [self, swatch_handle]()
        {
            // Settled rather than escaped: the full picker starts from what
            // was picked here, and keeps it if it is closed.
            if (ALFloaterLightBox* floater = self.get())
            {
                floater->closePopover(false);
            }
            if (LLColorSwatchCtrl* swatch = ALViewType::as<LLColorSwatchCtrl>(swatch_handle.get()))
            {
                swatch->showClassicPicker(true);
            }
        },
        getString("color_full_picker"), getString("color_full_picker_tooltip"));
    adoptPopover(PopoverKind::Color, popover, swatch);
    return true;
}

void ALFloaterLightBox::onColorPicked(const LLColor4& color)
{
    LLControlVariable* control = gSavedSettings.getControl(mColorKey);
    if (!control)
    {
        return;
    }
    // Live, as every row here is, and written the way the swatch writes a
    // Color3: three numbers, never a fourth.
    ScopedTrue writing(mColorWriting);
    control->setValue(LLColor3(color).getValue());
}

void ALFloaterLightBox::endColorSession(bool escaped)
{
    const std::string key = mColorKey;
    mColorKey.clear();
    LLControlVariable* control = key.empty() ? nullptr : gSavedSettings.getControl(key);
    if (!control)
    {
        return;
    }

    if (escaped)
    {
        // Escape keeps nothing, and nothing was recorded to take back.
        ScopedTrue writing(mColorWriting);
        control->setValue(mColorOriginal);
        return;
    }

    // The whole pick, as one step, from the colour it started at to the one it
    // was left at -- and none at all if it ended where it began.
    const LLSD picked = control->getValue();
    if (mRecordedKeys.count(key) && !llsd_equals(picked, mColorOriginal))
    {
        ScopedHistoryGroup group(mHistory);
        mHistory.record(key, mColorOriginal, picked, (F32)LLTimer::getElapsedSeconds().value());
    }
}

void ALFloaterLightBox::fitSections()
{
    // The margin under a section's last row, which is also what every
    // section's hand-kept height used to add.
    constexpr S32 BOTTOM_MARGIN = 8;

    for (const ALLightboxDirectory::Section& section : mDirectory.sections())
    {
        LLPanel* panel = section.mPanel;
        if (!panel)
        {
            continue;
        }
        // Every row follows the panel's top, so how far the lowest one reaches
        // down from it is the height the panel needs, whatever it was given.
        const S32 height = panel->getRect().getHeight();
        S32 lowest = height;
        for (const LLView* child : *panel->getChildList())
        {
            lowest = llmin(lowest, child->getRect().mBottom);
        }
        // Said to the tab the way everything that grows inside an accordion
        // says it: the tab takes the height plus its header and padding (or
        // remembers it, while it is shut) and asks the accordion to lay out
        // again. Sent whether or not it differs, so a tab declared at the
        // wrong height is put right as well.
        panel->notifyParent(LLSD().with("action", "size_changes")
                                  .with("height", height - lowest + BOTTOM_MARGIN));
    }
}

LLFloater* ALFloaterLightBox::paneWindow(size_t page) const
{
    if (page >= mPanes.size())
    {
        return nullptr;
    }
    const ALDockPanel* pane = ALViewType::as<ALDockPanel>(mPanes[page].mPane.get());
    return pane && pane->poppedOut() ? pane->getParentByType<LLFloater>() : nullptr;
}

void ALFloaterLightBox::togglePane()
{
    const S32 current = mTabs ? mTabs->getCurrentPanelIndex() : -1;
    if (current < 0 || (size_t)current >= mPanes.size())
    {
        return;
    }
    ALDockPanel* pane = ALViewType::as<ALDockPanel>(mPanes[current].mPane.get());
    if (!pane)
    {
        return;
    }

    if (pane->poppedOut())
    {
        dockPane((size_t)current);
        return;
    }

    // The keyboard is not taken along. A focused control moving to another
    // window, with this one still remembering it as where its focus was, is
    // how a keystroke ends up somewhere nobody is looking.
    if (gFocusMgr.childHasKeyboardFocus(pane))
    {
        gFocusMgr.setKeyboardFocus(nullptr);
    }
    gFocusMgr.clearLastFocusForGroup(this);
    pane->popOut();
    refreshPaneRow();
}

void ALFloaterLightBox::dockPane(size_t page)
{
    if (page >= mPanes.size())
    {
        return;
    }
    if (ALDockPanel* pane = ALViewType::as<ALDockPanel>(mPanes[page].mPane.get()))
    {
        if (pane->poppedOut())
        {
            pane->dock();
        }
    }
    refreshPaneRow();
}

void ALFloaterLightBox::dockPanes()
{
    for (const Pane& each : mPanes)
    {
        if (ALDockPanel* pane = ALViewType::as<ALDockPanel>(each.mPane.get()))
        {
            if (pane->poppedOut())
            {
                pane->dock();
            }
        }
    }
}

void ALFloaterLightBox::savePanes() const
{
    // By page name, so a page added or moved in the XUI keeps its own memory
    // and a page removed takes nobody else's with it.
    LLSD panes = LLSD::emptyMap();
    for (size_t index = 0; index < mPanes.size() && index < mTabPages.size(); ++index)
    {
        const ALDockPanel* pane = ALViewType::as<ALDockPanel>(mPanes[index].mPane.get());
        if (!pane)
        {
            continue;
        }
        LLSD entry = LLSD::emptyMap();
        entry["out"] = pane->poppedOut();
        const LLRect rect = pane->floatingRect();
        if (!rect.isEmpty())
        {
            entry["rect"] = rect.getValue();
        }
        panes[mTabPages[index]->getName()] = entry;
    }
    LLSD state = gSavedSettings.getLLSD("ALLightboxState");
    if (!state.isMap())
    {
        state = LLSD::emptyMap();
    }
    state["panes_out"] = panes;
    gSavedSettings.setLLSD("ALLightboxState", state);
}

void ALFloaterLightBox::restorePanes()
{
    const LLSD panes = gSavedSettings.getLLSD("ALLightboxState")["panes_out"];
    if (!panes.isMap())
    {
        return;
    }
    for (size_t index = 0; index < mPanes.size() && index < mTabPages.size(); ++index)
    {
        ALDockPanel* pane = ALViewType::as<ALDockPanel>(mPanes[index].mPane.get());
        const LLSD entry = panes[mTabPages[index]->getName()];
        if (!pane || !entry.isMap())
        {
            continue;
        }
        if (entry.has("rect"))
        {
            LLRect rect;
            rect.setValue(entry["rect"]);
            if (!rect.isEmpty())
            {
                pane->setFloatingRect(rect);
            }
        }
        if (entry["out"].asBoolean())
        {
            pane->popOut();
            // Where it was may be off a screen that has since gone.
            if (LLFloater* window = paneWindow(index))
            {
                gFloaterView->adjustToFitScreen(window, false);
            }
        }
    }
}

void ALFloaterLightBox::refreshPaneRow()
{
    if (mPanes.empty() || !mTabs)
    {
        return;
    }

    U32 out = 0;
    for (size_t index = 0; index < mPanes.size(); ++index)
    {
        const ALDockPanel* pane = ALViewType::as<ALDockPanel>(mPanes[index].mPane.get());
        if (pane && pane->poppedOut())
        {
            out |= 1u << index;
        }
    }
    const S32 current = mTabs->getCurrentPanelIndex();
    const S32 state = (S32)(out << 4) | (current & 0xF);
    if (state == mPaneRowState)
    {
        return;
    }
    mPaneRowState = state;

    for (size_t index = 0; index < mPanes.size(); ++index)
    {
        if (mPanes[index].mEmpty)
        {
            mPanes[index].mEmpty->setVisible(((out >> index) & 1) != 0);
        }
    }

    // The button speaks for the tab that is up: out, it brings the page
    // back; here, it sends it out.
    if (mPopOutButton && current >= 0)
    {
        const bool current_out = ((out >> current) & 1) != 0;
        mPopOutButton->setImageOverlay(current_out ? "Conv_toolbar_arrow_sw" : "Conv_toolbar_arrow_ne");
        LLStringUtil::format_map_t args;
        args["[TAB]"] = pageLabel((size_t)current);
        mPopOutButton->setToolTip(getString(current_out ? "pane_put_back_tooltip" : "pane_take_out_tooltip", args));
    }

    if (out != mPanesOutSaved)
    {
        mPanesOutSaved = out;
        savePanes();
    }
}

void ALFloaterLightBox::openHistory()
{
    constexpr S32 WIDTH = 340;
    constexpr S32 HEIGHT = 280;
    ALHistoryList::Params hp(LLUICtrlFactory::getDefaultParams<ALHistoryList>());
    hp.name = "lightbox_history_list";
    hp.rect = LLRect(0, HEIGHT, WIDTH, 0);
    hp.empty_headline = getString("history_empty_headline");
    hp.empty_sentence = getString("history_empty_sentence");
    ALHistoryList* list = LLUICtrlFactory::create<ALHistoryList>(hp);

    LLHandle<ALFloaterLightBox> self = getDerivedHandle<ALFloaterLightBox>();
    LLHandle<ALHistoryList> list_handle = list->getDerivedHandle<ALHistoryList>();
    LLView* anchor = mHistoryButton ? static_cast<LLView*>(mHistoryButton)
                                    : (mTopBar ? static_cast<LLView*>(mTopBar) : static_cast<LLView*>(this));
    ALPopover* popover = showPopover(PopoverKind::History, anchor, list,
        [self, list_handle](KEY key, MASK mask) -> bool
        {
            ALFloaterLightBox* floater = self.get();
            if (!floater)
            {
                return false;
            }
            if (key == KEY_RETURN && mask == MASK_NONE)
            {
                if (ALHistoryList* steps = list_handle.get())
                {
                    steps->goToSelected();
                }
                floater->closePopover(false);
                return true;
            }
            // The floater's own undo keys, stepping the list while it stays
            // up: watching the marker move is the point of having it open.
            const bool undo_key = (key == 'Z' && mask == MASK_CONTROL);
            const bool redo_key = (key == 'Y' && mask == MASK_CONTROL) ||
                                  (key == 'Z' && mask == (MASK_CONTROL | MASK_SHIFT));
            if (undo_key || redo_key)
            {
                floater->applyHistory(redo_key);
                return true;
            }
            if (key == 'F' && mask == MASK_CONTROL)
            {
                floater->openFind();
                return true;
            }
            return false;
        });
    if (!popover)
    {
        return;
    }

    mHistoryList = list->getHandle();
    list->onGoTo([self](size_t in_force)
    {
        // The list counts its first row, which is the start of the history
        // rather than a step, so the cursor is one less than it asks for.
        ALFloaterLightBox* floater = self.get();
        if (floater && in_force > 0)
        {
            floater->goToHistory(in_force - 1);
        }
    });
    fillHistoryList();
}

void ALFloaterLightBox::fillHistoryList()
{
    ALHistoryList* list = ALViewType::as<ALHistoryList>(mHistoryList.get());
    if (!list)
    {
        return;
    }
    mHistoryListRevision = mHistory.revision();

    // Nothing done yet: an empty list, which is what makes it say so.
    std::vector<ALHistoryList::Step> steps;
    if (mHistory.depth() == 0)
    {
        list->setSteps(std::move(steps), 0);
        return;
    }

    // A first row that is no step at all: where the history starts. Without
    // it no row could ask for nothing to be in force, and undoing everything
    // is the one trip back a person is most likely to want.
    steps.push_back({ getString("history_start"), std::string() });
    for (size_t index = 0; index < mHistory.depth(); ++index)
    {
        const ALGradeHistory::Transaction& changes = mHistory.at(index);
        ALHistoryList::Step step;
        step.what = mHistory.labelOf(index);
        if (step.what.empty())
        {
            if (changes.size() == 1)
            {
                step.what = mDirectory.captionFor(changes.front().mName);
            }
            else
            {
                LLStringUtil::format_map_t args;
                args["[COUNT]"] = llformat("%d", (S32)changes.size());
                step.what = getString("history_settings", args);
            }
        }

        // Where, when every change in the step is in one section: that is
        // what tells five Strength steps apart. A step across sections --
        // a Look, a section with an Advanced tail -- says it in its name.
        const ALLightboxDirectory::Section* common = nullptr;
        bool one_section = !changes.empty();
        for (const ALGradeHistory::Change& change : changes)
        {
            const ALLightboxDirectory::Section* in = mDirectory.sectionOf(change.mName);
            if (!in || (common && in != common))
            {
                one_section = false;
                break;
            }
            common = in;
        }
        if (one_section && common)
        {
            step.where = common->mTitle;
        }
        steps.push_back(std::move(step));
    }
    list->setSteps(std::move(steps), mHistory.cursor() + 1);
}

void ALFloaterLightBox::goToHistory(size_t cursor)
{
    // A step at a time through applyHistory, so every step is written back
    // exactly the way Ctrl+Z and Ctrl+Y write it. The guard is for a stack
    // that stops moving, which applyHistory reports rather than loops on.
    size_t guard = mHistory.depth() + 1;
    while (mHistory.cursor() > cursor && guard-- > 0)
    {
        if (!applyHistory(false))
        {
            break;
        }
    }
    while (mHistory.cursor() < cursor && guard-- > 0)
    {
        if (!applyHistory(true))
        {
            break;
        }
    }
}

std::string ALFloaterLightBox::pageLabel(size_t page) const
{
    return page < mTabPages.size() ? mTabPages[page]->getLabel() : std::string();
}

void ALFloaterLightBox::openFind()
{
    LLView* anchor = mTopBar ? static_cast<LLView*>(mTopBar) : static_cast<LLView*>(this);

    // As wide as the bar it hangs from, so it reads as the bar opening rather
    // than as another window.
    constexpr S32 HEIGHT = 300;
    const S32 width = llmax(anchor->getRect().getWidth(), 300);
    ALQuickOpen::Params qp(LLUICtrlFactory::getDefaultParams<ALQuickOpen>());
    qp.name = "lightbox_find_list";
    qp.rect = LLRect(0, HEIGHT, width, 0);
    qp.placeholder = getString("find_placeholder");
    ALQuickOpen* quick = LLUICtrlFactory::create<ALQuickOpen>(qp);

    // Sections as well as settings: the list matches what a row is called,
    // and "bloom" should reach the Bloom section even though none of its rows
    // says bloom. Each setting says which section it is in, which is what
    // tells the five Strength rows apart.
    std::vector<ALQuickOpen::Candidate> candidates;
    const std::vector<ALLightboxDirectory::Section>& sections = mDirectory.sections();
    for (size_t index = 0; index < sections.size(); ++index)
    {
        const ALLightboxDirectory::Section& section = sections[index];
        ALQuickOpen::Candidate here;
        here.label = section.mTitle;
        here.detail = pageLabel(section.mPage);
        here.value = "s:" + section.mName;
        candidates.push_back(std::move(here));
        for (const ALLightboxDirectory::Setting& setting : mDirectory.settings())
        {
            if (setting.mSection == index)
            {
                ALQuickOpen::Candidate row;
                row.label = setting.mCaption;
                row.detail = section.mTitle;
                row.value = "k:" + setting.mKey;
                candidates.push_back(std::move(row));
            }
        }
    }
    quick->setCandidates(std::move(candidates));

    // Ctrl+F again, with the list up, goes back to what was typed.
    LLHandle<ALQuickOpen> list = quick->getDerivedHandle<ALQuickOpen>();
    ALPopover* popover = showPopover(PopoverKind::Find, anchor, quick, [list](KEY key, MASK mask)
    {
        if (key == 'F' && mask == MASK_CONTROL)
        {
            if (ALQuickOpen* open = list.get())
            {
                open->takeFocus();
            }
            return true;
        }
        return false;
    });
    if (!popover)
    {
        return;
    }

    LLHandle<ALFloaterLightBox> self = getDerivedHandle<ALFloaterLightBox>();
    quick->onChose([self](const std::string& target)
    {
        if (ALFloaterLightBox* floater = self.get())
        {
            // Closed first, so the keyboard comes back to the Lightbox and
            // the jump can hand it on to the setting.
            floater->closePopover(false);
            floater->jumpTo(target);
        }
    });
    quick->takeFocus();
}

void ALFloaterLightBox::jumpTo(const std::string& target)
{
    const ALLightboxDirectory::Section* section = nullptr;
    const ALLightboxDirectory::Setting* setting = nullptr;
    if (target.compare(0, 2, "s:") == 0)
    {
        section = mDirectory.section(target.substr(2));
    }
    else if (target.compare(0, 2, "k:") == 0)
    {
        setting = mDirectory.setting(target.substr(2));
        if (setting)
        {
            section = &mDirectory.sections()[setting->mSection];
        }
    }
    if (!section)
    {
        return;
    }

    if (isMinimized())
    {
        setMinimized(false);
    }
    // A page out in a window of its own is shown by raising the window; its
    // tab here only says where it went.
    if (LLFloater* window = paneWindow(section->mPage))
    {
        if (window->isMinimized())
        {
            window->setMinimized(false);
        }
        window->setFrontmost(true);
    }
    else if (section->mPage < mTabPages.size())
    {
        mTabs->selectTabPanel(mTabPages[section->mPage]);
    }

    // Only the target's own tab is opened: an Advanced section is a sibling of
    // its essentials, not inside them. setDisplayChildren does not lay the
    // accordion out again, and the scroll below needs it laid out.
    if (section->mTab && !section->mTab->getDisplayChildren())
    {
        section->mTab->setDisplayChildren(true);
        if (section->mAccordion)
        {
            section->mAccordion->arrange();
        }
    }

    if (LLTextBox* was_lit = ALViewType::as<LLTextBox>(mLitCaption.get()))
    {
        was_lit->setHighlighted(false);
    }
    mLitCaption.markDead();

    if (setting && setting->mCtrl)
    {
        // Scrolled to the row, not to the section: a tall section scrolled to
        // shows its bottom, which is not where this row need be.
        setting->mCtrl->onUpdateScrollToChild(setting->mCtrl);
        setting->mCtrl->setFocus(true);
        if (setting->mCaptionBox)
        {
            setting->mCaptionBox->setHighlighted(true);
            mLitCaption = setting->mCaptionBox->getHandle();
            mLitTimer.reset();
        }
    }
    else if (section->mTab)
    {
        section->mTab->showAndFocusHeader();
    }
}

std::shared_ptr<LLSettingsDay> ALFloaterLightBox::getScrubbableDay() const
{
    // The order the viewer itself resolves environments in. ENV_LOCAL leads
    // because a day the user applied is the one they would expect to scrub;
    // while frozen it holds a fixed sky and has no day, so the search falls
    // through to whatever the parcel or region is running. That fall-through
    // is also what lets scrubbing keep working after the floater has been
    // closed and reopened, since nothing about it is remembered here.
    static const LLEnvironment::EnvSelection_t sources[] = {
        LLEnvironment::ENV_LOCAL, LLEnvironment::ENV_PUSH,
        LLEnvironment::ENV_PARCEL, LLEnvironment::ENV_REGION };

    for (LLEnvironment::EnvSelection_t env : sources)
    {
        if (LLSettingsDay::ptr_t day = LLEnvironment::instance().getEnvironmentDay(env))
        {
            return day;
        }
    }
    return {};
}

bool ALFloaterLightBox::isSkyFrozen() const
{
    return (bool)LLEnvironment::instance().getEnvironmentFixedSky(LLEnvironment::ENV_LOCAL);
}

void ALFloaterLightBox::applyDayPosition(F32 position)
{
    LLSettingsDay::ptr_t day = getScrubbableDay();
    if (!day)
    {
        return;
    }

    mDayPosition = llclamp(position, 0.f, 1.f);

    // A day cycle carries up to four sky tracks and which one you see depends
    // on how high you are, so sample the one the agent is actually in. Track 0
    // is water, always, and it gets sampled too: the day cycle editor blends
    // both and a frozen sky over a moving sea is not frozen.
    const S32 track = LLEnvironment::instance().calculateSkyTrackForAltitude(
        gAgent.getPositionAgent().mV[VZ]);

    LLSettingsSky::ptr_t sky = LLSettingsVOSky::buildDefaultSky();
    LLSettingsWater::ptr_t water = LLSettingsVOWater::buildDefaultWater();

    // make_shared rather than a temporary: LLSettingsBlender is held by shared
    // pointer internally, which is how the day cycle editor and @setenv_daytime
    // both spell this.
    std::make_shared<LLTrackBlenderLoopingManual>(sky, day, track)->setPosition(mDayPosition);
    std::make_shared<LLTrackBlenderLoopingManual>(water, day, (S32)LLSettingsDay::TRACK_WATER)
        ->setPosition(mDayPosition);

    LLEnvironment::instance().setEnvironment(LLEnvironment::ENV_LOCAL, sky, water);
    LLEnvironment::instance().setSelectedEnvironment(LLEnvironment::ENV_LOCAL, LLEnvironment::TRANSITION_INSTANT);
    LLEnvironment::instance().updateEnvironment(LLEnvironment::TRANSITION_INSTANT);
}

void ALFloaterLightBox::freezeSkyAt(F32 position)
{
    if (!mDayFreezeIsOurs)
    {
        // Whatever is here now is about to be covered up, and unticking Freeze
        // has to give it back. Without this, freezing over a Personal Lighting
        // sky and unfreezing again would quietly drop the user back to the
        // region default and lose their sky.
        LLEnvironment& env = LLEnvironment::instance();
        mPreFreezeDay = env.getEnvironmentDay(LLEnvironment::ENV_LOCAL);
        if (mPreFreezeDay)
        {
            mPreFreezeDayLength = env.getEnvironmentDayLength(LLEnvironment::ENV_LOCAL).value();
            mPreFreezeDayOffset = env.getEnvironmentDayOffset(LLEnvironment::ENV_LOCAL).value();
        }
        const LLEnvironment::fixedEnvironment_t fixed = env.getEnvironmentFixed(LLEnvironment::ENV_LOCAL);
        mPreFreezeSky = fixed.first;
        mPreFreezeWater = fixed.second;
        mDayFreezeIsOurs = true;
    }

    applyDayPosition(position);
}

void ALFloaterLightBox::thawSky()
{
    LLEnvironment& env = LLEnvironment::instance();

    // Every reflection probe in the scene was lit by the sky being replaced.
    // The World menu's own revert does this for the same reason; without it
    // the first frames after a thaw carry the light of the sky just left.
    gPipeline.mReflectionMapManager.reset();

    if (mDayFreezeIsOurs && mPreFreezeDay)
    {
        env.setEnvironment(LLEnvironment::ENV_LOCAL, mPreFreezeDay,
                           LLSettingsDay::Seconds(mPreFreezeDayLength),
                           LLSettingsDay::Seconds(mPreFreezeDayOffset));
    }
    else if (mDayFreezeIsOurs && (mPreFreezeSky || mPreFreezeWater))
    {
        env.setEnvironment(LLEnvironment::ENV_LOCAL, mPreFreezeSky, mPreFreezeWater);
    }
    else
    {
        // Nothing to give back, so fall through to the parcel or region.
        env.clearEnvironment(LLEnvironment::ENV_LOCAL);
    }

    env.setSelectedEnvironment(LLEnvironment::ENV_LOCAL, LLEnvironment::TRANSITION_INSTANT);
    env.updateEnvironment(LLEnvironment::TRANSITION_INSTANT);

    mPreFreezeDay.reset();
    mPreFreezeSky.reset();
    mPreFreezeWater.reset();
    mDayFreezeIsOurs = false;
}

void ALFloaterLightBox::refreshDayLandmarks()
{
    LLSettingsDay::ptr_t day = getScrubbableDay();
    if (day == mLandmarkDay)
    {
        return;
    }

    mLandmarkDay = day;
    mDayLandmarks = ALDayCycleLandmarks::Landmarks();
    if (!day)
    {
        return;
    }

    // One scratch sky, re-blended at each sample. getSunDirection's Z is the
    // sun's height above the horizon, which is the only thing that says where
    // noon is in a cycle whose keyframes could be anywhere.
    const S32 track = LLEnvironment::instance().calculateSkyTrackForAltitude(
        gAgent.getPositionAgent().mV[VZ]);
    LLSettingsSky::ptr_t scratch = LLSettingsVOSky::buildDefaultSky();
    auto blender = std::make_shared<LLTrackBlenderLoopingManual>(scratch, day, track);

    mDayLandmarks = ALDayCycleLandmarks::find(
        [&blender, &scratch](F32 position)
        {
            blender->setPosition(position);
            return scratch->getSunDirection().mV[VZ];
        });
}

void ALFloaterLightBox::refreshDayCycleRow()
{
    if (!mDayFreeze)
    {
        return; // the XUI is free to drop the row
    }

    const bool can_change = RlvActions::canChangeEnvironment();
    const bool frozen = isSkyFrozen();
    const bool has_day = (bool)getScrubbableDay();

    // While the sky is running, the slider shows where it actually is, so
    // ticking Freeze holds the moment being looked at rather than jumping.
    if (!frozen)
    {
        const F32 live = LLEnvironment::instance().getProgress();
        if (live >= 0.f)
        {
            mDayPosition = live;
            if (mDayTime)
            {
                mDayTime->setValue(mDayPosition);
            }
        }
        // A sky frozen by something else, then cleared by it, leaves us
        // holding a restore point for an environment that is already back.
        mDayFreezeIsOurs = false;
    }

    // Clouds are polled alongside because the World menu can pause them too,
    // and a checkbox that disagrees with the sky is worse than none.
    const bool clouds_paused = LLEnvironment::instance().isCloudScrollPaused();

    const S32 state = (can_change ? 1 : 0) | (frozen ? 2 : 0) | (has_day ? 4 : 0)
                    | (clouds_paused ? 8 : 0);
    if (state == mDayCycleRowState)
    {
        return;
    }
    mDayCycleRowState = state;

    if (mCloudScroll)
    {
        mCloudScroll->setValue(clouds_paused);
    }

    // @setenv is enforced inside LLEnvironment, not here, so without this the
    // controls would look live and do nothing at all under a restriction.
    mDayFreeze->setEnabled(can_change && has_day);
    mDayFreeze->setValue(frozen);
    if (mDayTime)
    {
        mDayTime->setEnabled(can_change && frozen && has_day);
    }
    if (mRestoreEnvironment)
    {
        mRestoreEnvironment->setEnabled(can_change && frozen);
    }

    // Presets cost a search, so only look when the row is actually usable.
    if (can_change && has_day)
    {
        refreshDayLandmarks();
    }
    const bool present[4] = { mDayLandmarks.has_sunrise, mDayLandmarks.has_noon,
                              mDayLandmarks.has_sunset, mDayLandmarks.has_midnight };
    for (size_t i = 0; i < mDayPresets.size(); ++i)
    {
        if (mDayPresets[i])
        {
            mDayPresets[i]->setEnabled(can_change && has_day && present[i]);
        }
    }
}

void ALFloaterLightBox::onToggleDayFreeze(LLUICtrl* ctrl)
{
    if (!ctrl)
    {
        return;
    }

    if (ctrl->getValue().asBoolean())
    {
        freezeSkyAt(mDayPosition);
    }
    else
    {
        thawSky();
    }
    mDayCycleRowState = -1;
}

void ALFloaterLightBox::onCommitDayTime(LLUICtrl* ctrl)
{
    if (ctrl)
    {
        // Through freezeSkyAt, not applyDayPosition, even though the slider is
        // only live while the sky is already frozen: "frozen" can also mean a
        // fixed sky somebody else installed -- Personal Lighting, say -- which
        // we have not captured. The first scrub over one of those is what
        // covers it up, so it is the moment to remember it, or unticking
        // Freeze drops the user to the region default instead of giving their
        // sky back. Once the freeze is ours the capture is skipped and this is
        // applyDayPosition, so a drag costs nothing extra per tick.
        freezeSkyAt((F32)ctrl->getValue().asReal());
    }
}

void ALFloaterLightBox::onClickDayPreset(const LLSD& userdata)
{
    refreshDayLandmarks();

    const std::string& which = userdata.asString();
    const ALDayCycleLandmarks::Landmarks& marks = mDayLandmarks;

    F32 position = 0.f;
    if (which == "sunrise" && marks.has_sunrise)        { position = marks.sunrise; }
    else if (which == "noon" && marks.has_noon)         { position = marks.noon; }
    else if (which == "sunset" && marks.has_sunset)     { position = marks.sunset; }
    else if (which == "midnight" && marks.has_midnight) { position = marks.midnight; }
    else                                                { return; }

    // A preset moves the slider and freezes there; it does not install a
    // canned sky, so the region's own idea of noon is what you get and you can
    // keep scrubbing from it.
    freezeSkyAt(position);
    if (mDayTime)
    {
        mDayTime->setValue(mDayPosition);
    }
    mDayCycleRowState = -1;
}

void ALFloaterLightBox::onToggleCloudScroll(LLUICtrl* ctrl)
{
    if (!ctrl)
    {
        return;
    }

    // Clouds drift on their own timer, entirely apart from the day cycle, so a
    // frozen sky with this off still has weather moving through it.
    if (ctrl->getValue().asBoolean())
    {
        LLEnvironment::instance().pauseCloudScroll();
    }
    else
    {
        LLEnvironment::instance().resumeCloudScroll();
    }
}

void ALFloaterLightBox::onClickRestoreEnvironment()
{
    // Unconditional, unlike unticking Freeze: this is the way back to the
    // parcel or region whatever we happen to be holding, including a sky some
    // other floater installed.
    mDayFreezeIsOurs = false;
    mPreFreezeDay.reset();
    mPreFreezeSky.reset();
    mPreFreezeWater.reset();
    thawSky();
    mDayCycleRowState = -1;
}

void ALFloaterLightBox::onGradeSettingChanged(const std::string& name, const LLSD& before, const LLSD& after)
{
    if (mApplyingHistory)
    {
        // Our own write, coming back round. Recording it would append the undo
        // to the stack it was taken from, and Ctrl+Z would toggle forever
        // between two values instead of walking backwards.
        return;
    }
    if (mColorWriting)
    {
        // The inline picker, moving. The pick is recorded whole when it ends.
        return;
    }

    // A monotonic clock is all the history wants: it compares two of these to
    // decide whether one drag is still in progress, and never reads the value
    // on its own.
    mHistory.record(name, before, after, (F32)LLTimer::getElapsedSeconds().value());
}

bool ALFloaterLightBox::applyHistory(bool redo_direction)
{
    // A pick still open has not been recorded yet, so the stack does not know
    // about it: put it back before stepping past it.
    if (mPopoverKind == PopoverKind::Color)
    {
        closePopover(true);
    }

    const ALGradeHistory::Transaction* stepp = redo_direction ? mHistory.redo() : mHistory.undo();
    if (!stepp)
    {
        return false;
    }

    // Copied, not followed. The pointer is into the history's own stack, and
    // while the guard below means nothing can record during the writes -- and
    // so nothing can resize that stack -- relying on it would make this
    // function's safety a property of code somewhere else. A transaction is a
    // handful of LLSD.
    const ALGradeHistory::Transaction step = *stepp;

    ScopedTrue applying(mApplyingHistory);
    for (const ALGradeHistory::Change& change : step)
    {
        if (LLControlVariable* controlp = gSavedSettings.getControl(change.mName))
        {
            controlp->setValue(redo_direction ? change.mAfter : change.mBefore);
        }
    }

    // Deliberately no attempt to restore which Look was active. Undo restores
    // values; the Look stays dirty, exactly as it would if the user had typed
    // the old numbers back in. See ALGradeHistory's header.
    return true;
}

bool ALFloaterLightBox::handleKeyHere(KEY key, MASK mask)
{
    // Both spellings of redo: Ctrl+Y is the Windows convention and
    // Ctrl+Shift+Z the one every grading application uses.
    if (key == 'F' && mask == MASK_CONTROL)
    {
        openFind();
        return true;
    }

    const bool undo_key = (key == 'Z' && mask == MASK_CONTROL);
    const bool redo_key = (key == 'Y' && mask == MASK_CONTROL) ||
                          (key == 'Z' && mask == (MASK_CONTROL | MASK_SHIFT));
    if (undo_key || redo_key)
    {
        // hasAccelerators means these arrive before the menu bar has seen
        // them, so the Edit menu's own undo -- which is what a text control
        // with an edit history of its own would have got from them -- is
        // offered here instead, and only a key it declines reaches the grade.
        LLEditMenuHandler* text = LLEditMenuHandler::gEditMenuHandler;
        LLView* text_view = text ? text->asView() : nullptr;
        if (text_view && text_view->hasAncestor(this))
        {
            if (undo_key && text->canUndo())
            {
                text->undo();
                return true;
            }
            if (redo_key && text->canRedo())
            {
                text->redo();
                return true;
            }
        }

        applyHistory(redo_key);
        return true;
    }

    return LLFloater::handleKeyHere(key, mask);
}

void ALFloaterLightBox::onCommitVec3(LLUICtrl* ctrl)
{
    if (mVec3Updating || !ctrl)
    {
        return;
    }

    std::string setting;
    S32 component = 0;
    if (!ALLightboxDirectory::parseVec3Name(ctrl->getName(), setting, component))
    {
        return;
    }

    LLControlVariable* controlp = gSavedSettings.getControl(setting);
    if (!controlp)
    {
        return;
    }

    // Rebuild the full component array so a single spinner commit writes back
    // one component without disturbing the others; works for VEC3 and COL3.
    const LLSD current = controlp->getValue();
    LLSD updated = LLSD::emptyArray();
    for (S32 i = 0; i < 3; ++i)
    {
        updated.append(LLSD::Real(current[i].asReal()));
    }
    updated[component] = LLSD::Real(ctrl->getValue().asReal());
    controlp->set(updated);
}

namespace
{
// The four curve settings are loaded fresh on every refresh and commit rather
// than mirrored in a member: the settings are the truth, and undo, Looks and
// Debug Settings all write them behind the floater's back. Their names live
// on ALToneCurveSet, the one list the renderer and the Looks whitelist share.
ALToneCurveSet loadToneCurveSet()
{
    ALToneCurveSet curves;
    for (S32 c = 0; c < ALToneCurveSet::CH_COUNT; ++c)
    {
        const ALToneCurveSet::EChannel channel = static_cast<ALToneCurveSet::EChannel>(c);
        curves.setCurveFromLLSD(channel, gSavedSettings.getLLSD(ALToneCurveSet::settingName(channel)));
    }
    return curves;
}

// Ghosts of the channels not being edited, and the solid handle colour of the
// one that is: the same three hues, dim and bright.
const LLColor4 CHANNEL_TINT[3] = {
    LLColor4(0.8f, 0.25f, 0.25f, 0.55f),
    LLColor4(0.25f, 0.8f, 0.35f, 0.55f),
    LLColor4(0.35f, 0.5f, 0.9f, 0.55f) };
const LLColor4 CHANNEL_SOLID[3] = {
    LLColor4(0.9f, 0.3f, 0.3f, 1.f),
    LLColor4(0.3f, 0.85f, 0.4f, 1.f),
    LLColor4(0.4f, 0.55f, 0.95f, 1.f) };
// What a channel actually gets once Master is applied after it.
const LLColor4 COMPOSITE_TINT(0.85f, 0.85f, 0.85f, 0.4f);

// The split-toning settings the band graph reads. The tints colour the bands,
// the amounts fade them, and the balance and the two widths are what its
// three handles write.
const char* const SPLIT_TONE_SHADOW          = "RenderSplitToneShadowTint";
const char* const SPLIT_TONE_MIDTONE         = "RenderSplitToneMidtoneTint";
const char* const SPLIT_TONE_HIGHLIGHT       = "RenderSplitToneHighlightTint";
const char* const SPLIT_TONE_AMOUNT          = "RenderSplitToneAmount";
const char* const SPLIT_TONE_MIDTONE_AMOUNT  = "RenderSplitToneMidtoneAmount";
const char* const SPLIT_TONE_BALANCE         = "RenderSplitToneBalance";
const char* const SPLIT_TONE_SHADOW_WIDTH    = "RenderSplitToneShadowWidth";
const char* const SPLIT_TONE_HIGHLIGHT_WIDTH = "RenderSplitToneHighlightWidth";

// The range an edge handle clamps a width into is the width slider's own,
// read from the widget so the XUI stays the single home of it. The renderer
// itself only floors a width (ALCurveModel::SPLIT_TONE_MIN_WIDTH), so Debug
// Settings can still ask for more; the graph and the render agree either
// way, because both go through the model. A dropped slider falls back to the
// floor and the domain.
void widthRange(const LLSliderCtrl* slider, F32& lo, F32& hi)
{
    lo = ALCurveModel::SPLIT_TONE_MIN_WIDTH;
    hi = 1.f;
    if (slider)
    {
        lo = slider->getMinValue();
        hi = slider->getMaxValue();
    }
}

LLColor3 getColor3(const char* key)
{
    return gSavedSettings.getColor3(key);
}
} // namespace

S32 ALFloaterLightBox::getToneCurveChannel() const
{
    return mToneCurveChannel ? mToneCurveChannel->getValue().asInteger() : -1;
}

void ALFloaterLightBox::setupToneCurve()
{
    mToneCurve = findChild<ALCurveEditorCtrl>("tone_curve_graph");
    if (!mToneCurve)
    {
        return;
    }
    mToneCurveChannel = findChild<LLComboBox>("tone_curve_channel");
    if (mToneCurveChannel)
    {
        // Start on Master. Without an explicit selection an unselected combo
        // reads back as 0, which would silently mean "red only".
        mToneCurveChannel->selectByValue(LLSD(-1));
    }

    for (S32 c = 0; c < ALToneCurveSet::CH_COUNT; ++c)
    {
        const char* key = ALToneCurveSet::settingName(static_cast<ALToneCurveSet::EChannel>(c));
        if (LLControlVariable* controlp = gSavedSettings.getControl(key))
        {
            mToneCurveConnections.emplace_back(controlp->getSignal()->connect(
                [this](LLControlVariable*, const LLSD&, const LLSD&) { refreshToneCurve(); }));
        }
    }

    // The graph names the settings it edits in XUI so the section's Reset All
    // can find them; a typo there fails silently, so say so once.
    for (const std::string& name : mToneCurve->getEditedSettingNames())
    {
        if (!gSavedSettings.getControl(name))
        {
            LL_WARNS() << "tone_curve_graph names an unknown setting: " << name << LL_ENDL;
        }
    }

    refreshToneCurve();
}

void ALFloaterLightBox::refreshToneCurve()
{
    if (!mToneCurve || mToneCurveUpdating)
    {
        return;
    }

    const ALToneCurveSet curves = loadToneCurveSet();
    const ALToneCurveSet::EChannel channel = ALToneCurveSet::channelFromCombo(getToneCurveChannel());
    // A copy: the lambdas below outlive this call.
    const ALCurveModel selected = curves.curve(channel);

    // The selected curve alone is what is drawn solid. Its points are the
    // handles, so what is seen is exactly what a drag edits.
    mToneCurve->setCurve([selected](F32 x) { return selected.evaluate(x); });

    mToneCurve->clearGhostCurves();
    if (channel != ALToneCurveSet::CH_MASTER &&
        !ALToneCurveSet::isIdentityCurve(curves.curve(ALToneCurveSet::CH_MASTER)))
    {
        // What this channel actually gets once Master is applied after it.
        mToneCurve->addGhostCurve([curves, channel](F32 x) { return curves.evaluate(channel, x); }, COMPOSITE_TINT);
    }
    for (S32 i = 0; i < 3; ++i)
    {
        const ALToneCurveSet::EChannel other = static_cast<ALToneCurveSet::EChannel>(ALToneCurveSet::CH_RED + i);
        if (other == channel || ALToneCurveSet::isIdentityCurve(curves.curve(other)))
        {
            continue;
        }
        const ALCurveModel ghost = curves.curve(other);
        mToneCurve->addGhostCurve([ghost](F32 x) { return ghost.evaluate(x); }, CHANNEL_TINT[i]);
    }

    // One handle per point, in point order: getActiveHandle() is then the
    // point index, which is the whole contract onCommitToneCurve relies on.
    std::vector<ALCurveEditorCtrl::Handle> handles;
    const std::vector<ALCurveModel::Point>& points = selected.getPoints();
    for (size_t i = 0; i < points.size(); ++i)
    {
        ALCurveEditorCtrl::Handle h;
        const bool endpoint = (i == 0 || i + 1 == points.size());
        h.mX = points[i].mX;
        h.mY = points[i].mY;
        // The model pins the ends too; the lock stops the pointer fighting it.
        h.mLockX = endpoint;
        h.mColor = (channel == ALToneCurveSet::CH_MASTER)
                       ? LLColor4::white
                       : CHANNEL_SOLID[channel - ALToneCurveSet::CH_RED];
        handles.push_back(h);
    }
    mToneCurve->setHandles(std::move(handles));
}

void ALFloaterLightBox::onCommitToneCurve()
{
    if (!mToneCurve)
    {
        return;
    }
    const ALCurveEditorCtrl::EAction action = mToneCurve->getAction();
    if (action == ALCurveEditorCtrl::ACTION_NONE)
    {
        return;
    }

    const ALToneCurveSet::EChannel channel = ALToneCurveSet::channelFromCombo(getToneCurveChannel());
    LLControlVariable* controlp = gSavedSettings.getControl(ALToneCurveSet::settingName(channel));
    if (!controlp)
    {
        return;
    }

    ALToneCurveSet curves = loadToneCurveSet();
    ALCurveModel& curve = curves.curve(channel);

    bool changed = false;
    switch (action)
    {
        case ALCurveEditorCtrl::ACTION_DRAG:
        {
            const S32 index = mToneCurve->getActiveHandle();
            if (index < 0 || index >= curve.getPointCount() || index >= (S32)mToneCurve->getHandles().size())
            {
                return;
            }
            // By value: the refresh below replaces the handle list.
            const ALCurveEditorCtrl::Handle handle = mToneCurve->getHandles()[index];
            // Clamps into the neighbours' gap; the ends stay pinned.
            curve.movePoint(index, handle.mX, handle.mY);
            changed = true;
            break;
        }
        case ALCurveEditorCtrl::ACTION_ADD:
            // Past the cap the click is simply ignored, which is the honest
            // answer; the tooltip states the limit.
            changed = curve.addPoint(mToneCurve->getActionX(), mToneCurve->getActionY()) >= 0;
            break;
        case ALCurveEditorCtrl::ACTION_REMOVE:
        {
            // The same bound the drag has: the handle list and the point list
            // are built from each other, but the setting can move between.
            const S32 index = mToneCurve->getActiveHandle();
            if (index < 0 || index >= curve.getPointCount())
            {
                return;
            }
            // False for an endpoint or a two-point curve.
            changed = curve.removePoint(index);
            break;
        }
        default:
            break;
    }

    if (!changed)
    {
        // Put the handle back where the model kept the point.
        refreshToneCurve();
        return;
    }

    // One setting per commit: that is what lets the history coalesce a drag
    // into a single undo step. Writing a setting re-enters through its
    // signal; let the write land, then rebuild the handles once from the
    // values that actually stuck. Scoped so no early return can leave the
    // flag stuck, and closed before the refresh below, which reads it.
    {
        ScopedTrue updating(mToneCurveUpdating);
        controlp->set(ALToneCurveSet::pointsToLLSD(curve.getPoints()));
    }
    refreshToneCurve();
}

void ALFloaterLightBox::onClickResetToneCurveChannel()
{
    // resetToDefault fires the setting's signal, which refreshes the graph.
    const ALToneCurveSet::EChannel channel = ALToneCurveSet::channelFromCombo(getToneCurveChannel());
    if (LLControlVariable* controlp = gSavedSettings.getControl(ALToneCurveSet::settingName(channel)))
    {
        controlp->resetToDefault(true);
    }
}

void ALFloaterLightBox::onToneCurvePreset(const LLSD& userdata)
{
    // Point lists, both axes 0..1, with the ends at x = 0 and 1 as the model
    // pins them. Modest on purpose: a preset is a starting shape.
    typedef std::vector<ALCurveModel::Point> points_t;
    static const std::map<std::string, points_t> presets = {
        { "linear",   { { 0.f, 0.f }, { 1.f, 1.f } } },
        { "soft_s",   { { 0.f, 0.f }, { 0.25f, 0.21f }, { 0.75f, 0.79f }, { 1.f, 1.f } } },
        { "strong_s", { { 0.f, 0.f }, { 0.25f, 0.16f }, { 0.75f, 0.84f }, { 1.f, 1.f } } },
        { "fade",     { { 0.f, 0.08f }, { 0.3f, 0.32f }, { 1.f, 1.f } } },
        { "matte",    { { 0.f, 0.08f }, { 0.3f, 0.32f }, { 0.75f, 0.76f }, { 1.f, 0.94f } } },
    };
    const auto found = presets.find(userdata.asString());
    if (found == presets.end())
    {
        return;
    }

    ALCurveModel curve;
    curve.setPoints(found->second);

    // One setting, the selected curve; its signal refreshes the graph. No
    // re-entry guard: nothing is mid-drag.
    const ALToneCurveSet::EChannel channel = ALToneCurveSet::channelFromCombo(getToneCurveChannel());
    if (LLControlVariable* controlp = gSavedSettings.getControl(ALToneCurveSet::settingName(channel)))
    {
        controlp->set(ALToneCurveSet::pointsToLLSD(curve.getPoints()));
    }
}

void ALFloaterLightBox::setupSplitToneGraph()
{
    mSplitToneGraph = findChild<ALCurveEditorCtrl>("split_tone_graph");
    if (!mSplitToneGraph)
    {
        return;
    }
    // The widths are setting rows; the range widthRange reads is still the
    // slider's own, reached through its row.
    if (ALSettingRow* row = findChild<ALSettingRow>("split_shadow_width"))
    {
        mSplitShadowWidthSlider = row->getSlider();
    }
    if (ALSettingRow* row = findChild<ALSettingRow>("split_highlight_width"))
    {
        mSplitHighlightWidthSlider = row->getSlider();
    }

    // Every input, not just the three the handles write: the tints decide
    // what colour a band is drawn in and the amounts decide how solid, so a
    // graph that only watched its own settings would sit there showing a
    // tint the renderer had already stopped applying.
    for (const char* key : { SPLIT_TONE_SHADOW, SPLIT_TONE_MIDTONE, SPLIT_TONE_HIGHLIGHT,
                             SPLIT_TONE_AMOUNT, SPLIT_TONE_MIDTONE_AMOUNT, SPLIT_TONE_BALANCE,
                             SPLIT_TONE_SHADOW_WIDTH, SPLIT_TONE_HIGHLIGHT_WIDTH })
    {
        if (LLControlVariable* controlp = gSavedSettings.getControl(key))
        {
            mSplitToneConnections.emplace_back(controlp->getSignal()->connect(
                [this](LLControlVariable*, const LLSD&, const LLSD&) { refreshSplitToneGraph(); }));
        }
    }

    refreshSplitToneGraph();
}

void ALFloaterLightBox::refreshSplitToneGraph()
{
    if (!mSplitToneGraph || mSplitToneUpdating)
    {
        return;
    }

    const F32 mid = ALCurveModel::splitToneMid(gSavedSettings.getF32(SPLIT_TONE_BALANCE));
    const F32 amount     = llclamp(gSavedSettings.getF32(SPLIT_TONE_AMOUNT), 0.f, 1.f);
    const F32 mid_amount = llclamp(gSavedSettings.getF32(SPLIT_TONE_MIDTONE_AMOUNT), 0.f, 1.f);
    // Not clamped to the slider range: the model floors a width the way the
    // renderer does, so the bands show what is actually being applied even
    // when Debug Settings asked for something the sliders would not.
    const F32 ws = gSavedSettings.getF32(SPLIT_TONE_SHADOW_WIDTH);
    const F32 wh = gSavedSettings.getF32(SPLIT_TONE_HIGHLIGHT_WIDTH);

    // A band wears the tint it applies. Normalised the way pipeline.cpp
    // normalises it, so what the graph shows is the hue the renderer will
    // actually use and a tint that is merely bright reads as neutral -- which
    // is the truth, since the shader divides that brightness back out.
    auto band_color = [](const char* key, F32 strength)
    {
        const LLColor3 tint = getColor3(key);
        constexpr F32 LUMA_R = 0.2126f, LUMA_G = 0.7152f, LUMA_B = 0.0722f;
        const F32 luma = llmax(tint.mV[0] * LUMA_R + tint.mV[1] * LUMA_G + tint.mV[2] * LUMA_B, 1e-4f);

        // Half brightness so a neutral band is mid grey and a saturated one has
        // room to read as itself without clipping to white.
        constexpr F32 DISPLAY_LEVEL = 0.5f;
        LLColor4 out(llclamp(tint.mV[0] / luma * DISPLAY_LEVEL, 0.f, 1.f),
                     llclamp(tint.mV[1] / luma * DISPLAY_LEVEL, 0.f, 1.f),
                     llclamp(tint.mV[2] / luma * DISPLAY_LEVEL, 0.f, 1.f),
                     1.f);
        // Alpha follows the amount, so a band the renderer is ignoring fades
        // instead of sitting at full strength claiming otherwise. It never
        // reaches zero: where the bands lie is worth seeing even when nothing
        // is being applied, and that is what the handles move.
        out.mV[VALPHA] = 0.16f + 0.44f * strength;
        return out;
    };

    mSplitToneGraph->clearFillCurves();
    mSplitToneGraph->addFillCurve(
        [mid, ws, wh](F32 l) { return ALCurveModel::splitToneWeights(l, mid, ws, wh).mShadow; },
        band_color(SPLIT_TONE_SHADOW, amount));
    mSplitToneGraph->addFillCurve(
        [mid, ws, wh](F32 l) { return ALCurveModel::splitToneWeights(l, mid, ws, wh).mMidtone; },
        band_color(SPLIT_TONE_MIDTONE, mid_amount));
    mSplitToneGraph->addFillCurve(
        [mid, ws, wh](F32 l) { return ALCurveModel::splitToneWeights(l, mid, ws, wh).mHighlight; },
        band_color(SPLIT_TONE_HIGHLIGHT, amount));

    // Three handles along the top edge, all held to the horizontal because
    // moving any of them up or down would mean nothing. Balance first, so a
    // tie in the hit test goes to the split point. It rides the peak of the
    // midtone band, where the two ramps hand over.
    ALCurveEditorCtrl::Handle balance;
    balance.mName = "balance";
    balance.mX = mid;
    balance.mY = 1.f;
    balance.mLockY = true;

    // The edges are the corners where the shadow band starts to fall away and
    // where the highlight band reaches full strength, at the width the model
    // actually renders -- floored like the ramp, so a zero or negative width
    // from Debug Settings puts the handle where the band really ends. A ramp
    // that runs off the plot has its handle held at the edge, locked and
    // dimmed: the only positions a drag could report from there lie inside
    // the plot, and writing one back would silently replace a wide ramp with
    // a narrow one. The slider is the control for that case, and the commit
    // refuses a locked handle.
    auto edge_handle = [&band_color, amount](const char* name, F32 true_x, const char* tint_key)
    {
        ALCurveEditorCtrl::Handle h;
        h.mName = name;
        h.mX = llclamp(true_x, 0.f, 1.f);
        h.mY = 1.f;
        h.mLockY = true;
        const bool parked = (true_x < 0.f || true_x > 1.f);
        h.mLockX = parked;
        h.mColor = band_color(tint_key, amount);
        h.mColor.mV[VALPHA] = parked ? 0.5f : 1.f;
        return h;
    };
    const F32 ws_drawn = llmax(ws, ALCurveModel::SPLIT_TONE_MIN_WIDTH);
    const F32 wh_drawn = llmax(wh, ALCurveModel::SPLIT_TONE_MIN_WIDTH);

    mSplitToneGraph->setHandles({ balance,
                                  edge_handle("shadow_edge", mid - ws_drawn, SPLIT_TONE_SHADOW),
                                  edge_handle("highlight_edge", mid + wh_drawn, SPLIT_TONE_HIGHLIGHT) });
}

void ALFloaterLightBox::onCommitSplitToneGraph()
{
    // Only a drag means anything here. The graph never asks for points, but a
    // future XUI that set points_editable must not turn a double-click into a
    // balance write.
    if (!mSplitToneGraph || mSplitToneGraph->getAction() != ALCurveEditorCtrl::ACTION_DRAG)
    {
        return;
    }
    const S32 index = mSplitToneGraph->getActiveHandle();
    if (index < 0 || index >= (S32)mSplitToneGraph->getHandles().size())
    {
        return;
    }
    const ALCurveEditorCtrl::Handle handle = mSplitToneGraph->getHandles()[index];
    const F32 mid = ALCurveModel::splitToneMid(gSavedSettings.getF32(SPLIT_TONE_BALANCE));

    // Dragged past its range, the value clamps and the refresh below puts the
    // handle back where the setting actually landed, rather than leaving it
    // parked somewhere the renderer will not follow. One setting per handle:
    // the balance drag moves both edges by writing only the balance, which is
    // what keeps a drag one undo step. An edge handle held at the plot edge
    // (mLockX, see refreshSplitToneGraph) writes nothing: its position is not
    // the width, and the width slider is the control for it.
    //
    // Scoped for the same reason the tone curve guard is, and closed before
    // the refresh for the same reason too.
    {
        ScopedTrue updating(mSplitToneUpdating);
        if (handle.mName == "balance")
        {
            gSavedSettings.setF32(SPLIT_TONE_BALANCE, ALCurveModel::splitToneBalance(handle.mX));
        }
        else if (handle.mName == "shadow_edge" && !handle.mLockX)
        {
            F32 lo, hi;
            widthRange(mSplitShadowWidthSlider, lo, hi);
            gSavedSettings.setF32(SPLIT_TONE_SHADOW_WIDTH, llclamp(mid - handle.mX, lo, hi));
        }
        else if (handle.mName == "highlight_edge" && !handle.mLockX)
        {
            F32 lo, hi;
            widthRange(mSplitHighlightWidthSlider, lo, hi);
            gSavedSettings.setF32(SPLIT_TONE_HIGHLIGHT_WIDTH, llclamp(handle.mX - mid, lo, hi));
        }
    }
    refreshSplitToneGraph();
}

void ALFloaterLightBox::onClickWhiteBalancePicker()
{
    ALToolScenePicker* picker = ALToolScenePicker::getInstance();

    // A handle, not `this`. Two gaps let this floater die first: the tool stays
    // armed until something is clicked, and the sample itself only arrives a
    // frame after the click. This floater declares neither single_instance nor
    // reuse_instance, so LLFloater::closeFloater destroys it outright -- arm
    // the picker, close the Lightbox, click the world, and a raw pointer would
    // be a use-after-free.
    LLHandle<ALFloaterLightBox> handle = getDerivedHandle<ALFloaterLightBox>();
    picker->setPickCallback([handle](const LLColor3& sample)
    {
        if (ALFloaterLightBox* self = handle.get())
        {
            self->onWhiteBalancePicked(sample);
        }
    });

    LLToolMgr::getInstance()->setTransientTool(picker);
}

void ALFloaterLightBox::onWhiteBalancePicked(const LLColor3& sample)
{
    // The ratios of three near-zero numbers are noise, and a sample in shadow
    // is exactly where a click lands when someone misses. Refuse rather than
    // swing the sliders to an answer read out of rounding error.
    constexpr F32 MIN_LUMA = 1e-3f;
    const F32 luma = sample.mV[0] * 0.2126f + sample.mV[1] * 0.7152f + sample.mV[2] * 0.0722f;
    if (luma < MIN_LUMA)
    {
        LLNotificationsUtil::add("LightBoxWhiteBalanceTooDark");
        return;
    }

    const ALWhiteBalanceSolver::Result solved = ALWhiteBalanceSolver::solveForColor(sample);

    // Past this the sliders cannot express what was asked for -- a strongly
    // coloured surface, not a neutral one lit by coloured light. Applying the
    // nearest reachable balance would look like the tool misfiring, so say so
    // and change nothing. The threshold is well clear of the ~1e-3 a genuine
    // solve returns and well below the 0.1-plus of a saturated sample.
    constexpr F32 MAX_RESIDUAL = 0.02f;
    if (solved.mResidual > MAX_RESIDUAL)
    {
        LLNotificationsUtil::add("LightBoxWhiteBalanceUnreachable");
        return;
    }

    // One pick is one thing the user did, though it moves two sliders: without
    // the group it undid as two steps, temperature first and then tint.
    ScopedHistoryGroup group(mHistory, getString("history_white_balance"));
    gSavedSettings.setF32("RenderColorGradeWhiteBalanceCCT", solved.mCCTOffset);
    gSavedSettings.setF32("RenderColorGradeWhiteBalanceDuv", solved.mDuv);
}

void ALFloaterLightBox::onLookSelected()
{
    const std::string name = mLooksCombo ? mLooksCombo->getSimple() : std::string();
    if (!name.empty())
    {
        // Applying a Look writes every whitelisted key it carries. That is one
        // choice, so it is one undo step -- and it is the step a user most
        // wants back, having tried a Look on top of work they liked.
        LLStringUtil::format_map_t args;
        args["[NAME]"] = name;
        ScopedHistoryGroup group(mHistory, getString("history_look", args));
        LLPresetsManager::getInstance()->loadLooksPreset(name);
    }
}

void ALFloaterLightBox::onClickLookSave()
{
    std::string name = gSavedSettings.getString("PresetLooksActive");
    if (name.empty())
    {
        name = gSavedSettings.getString("PresetLooksLastApplied");
    }
    if (name.empty())
    {
        // Nothing to overwrite yet; fall through to the name dialog
        onClickLookSaveAs();
        return;
    }
    LLPresetsManager::getInstance()->savePreset(PRESETS_LOOKS, name);
}

void ALFloaterLightBox::onClickLookSaveAs()
{
    LLFloaterReg::showInstance("save_pref_preset", LLSD(PRESETS_LOOKS));
}

void ALFloaterLightBox::onClickLookDelete()
{
    LLFloaterReg::showInstance("delete_pref_preset", LLSD(PRESETS_LOOKS));
}

void ALFloaterLightBox::onClickLookRevert()
{
    const std::string last = gSavedSettings.getString("PresetLooksLastApplied");
    if (!last.empty())
    {
        // Same reasoning as onLookSelected: a revert throws away every edit
        // since the Look was applied, and that had better be one Ctrl+Z.
        LLStringUtil::format_map_t args;
        args["[NAME]"] = last;
        ScopedHistoryGroup group(mHistory, getString("history_revert", args));
        LLPresetsManager::getInstance()->loadLooksPreset(last);
    }
}

void ALFloaterLightBox::refreshLooksBar()
{
    if (!mLooksCombo)
    {
        return;
    }

    LLPresetsManager::getInstance()->setPresetNamesInComboBox(PRESETS_LOOKS, mLooksCombo, DEFAULT_HIDE);

    const std::string active = gSavedSettings.getString("PresetLooksActive");
    const std::string last = gSavedSettings.getString("PresetLooksLastApplied");
    const bool modified = active.empty() && !last.empty();
    if (!active.empty())
    {
        mLooksCombo->selectByValue(active);
    }
    else if (!last.empty())
    {
        // The modified marker rides the name rather than sitting beside it as
        // its own widget. Attached, it says which Look has been changed; a
        // detached asterisk only says that something somewhere has.
        //
        // Display only: nothing selects while modified, which is the state
        // this branch is, and onLookSelected reads the chosen item's own text
        // rather than the combo's label -- so the marker cannot travel into a
        // Look name.
        LLStringUtil::format_map_t args;
        args["[NAME]"] = last;
        mLooksCombo->setLabel(getString("look_name_modified", args));
    }
    if (mLookSave)
    {
        mLookSave->setEnabled(!active.empty() || !last.empty());
    }
    if (mLookDelete)
    {
        mLookDelete->setEnabled(mLooksCombo->getItemCount() > 0);
    }
    if (mLookRevert)
    {
        mLookRevert->setEnabled(modified);
    }
}

void ALFloaterLightBox::updateTonemapperRows()
{
    const S32 type = gSavedSettings.getS32("AlchemyRenderTonemapType");
    for (const TonemapperRow& row : mTonemapperRows)
    {
        if (row.mCtrl)
        {
            row.mCtrl->setEnabled(type == row.mType);
        }
    }
}

void ALFloaterLightBox::refreshVec3Row(const std::string& setting_name)
{
    auto row = mVec3Rows.find(setting_name);
    LLControlVariable* controlp = gSavedSettings.getControl(setting_name);
    if (row == mVec3Rows.end() || !controlp)
    {
        return;
    }

    const LLSD value = controlp->getValue();
    ScopedTrue updating(mVec3Updating);
    for (S32 i = 0; i < 3; ++i)
    {
        if (LLUICtrl* ctrlp = row->second[i])
        {
            ctrlp->setValue(value[i].asReal());
        }
    }
}
