/**
 * @file alfloaterlightbox.h
 * @brief Lightbox post-processing control floater
 *
 * Copyright (c) Rye Mutt <rye@alchemyviewer.org>
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#pragma once

#ifndef AL_FLOATERLIGHTBOX_H
#define AL_FLOATERLIGHTBOX_H

#include "llfloater.h"
#include "llframetimer.h"

#include "aldaycyclelandmarks.h"
#include "algradehistory.h"
#include "allightboxdirectory.h"

#include <array>
#include <functional>
#include <map>
#include <memory>
#include <string>
#include <vector>

class ALCurveEditorCtrl;
class ALPopover;
class LLComboBox;
class LLPanel;
class LLSettingsDay;
class LLSettingsSky;
class LLSettingsWater;
class LLSliderCtrl;
class LLSpinCtrl;
class LLTabContainer;

class ALFloaterLightBox final : public LLFloater
{
public:
    AL_VIEW_TYPE(ALFloaterLightBox, LLFloater);

    ALFloaterLightBox(const LLSD& key);
    ~ALFloaterLightBox() override;
    bool postBuild() override;
    /// Ctrl+Z / Ctrl+Y (and Ctrl+Shift+Z) drive the grade's undo stack.
    ///
    /// Floater-local rather than a global action, unlike the hold-to-compare
    /// key: a global Ctrl+Z would fire while the user is typing anywhere in
    /// the viewer. A focused text control with an edit history of its own
    /// keeps these keys for it.
    bool handleKeyHere(KEY key, MASK mask) override;
    /// Ctrl and Alt keys go to the menu bar's accelerators before the focused
    /// floater unless something in the focus chain claims accelerators of its
    /// own, so without this Ctrl+Shift+Z never reached handleKeyHere at all:
    /// it is World > Environment > Midnight, and pressing it in the Lightbox
    /// set the sky to midnight instead of redoing. Claiming them costs nothing
    /// else -- a key this floater does not handle falls through to the menus
    /// exactly as before.
    bool hasAccelerators() const override { return true; }
    /// Only to notice the reference still appearing or going away, which is
    /// render state and so has no signal to hang on. See refreshReferenceRow.
    void draw() override;
    /// A popover still up is closed as settled first: whatever it was showing
    /// was chosen, and it must not outlive the floater its callbacks reach.
    void onClose(bool app_quitting) override;

  private:
    /// What the popover that is up, if any, is for.
    enum class PopoverKind
    {
        None,
        Find,
    };
    /// A key the popover gets first while it has the keyboard: the floater's
    /// own shortcuts, which would otherwise fall to the menu bar.
    using PopoverKeyHook = std::function<bool(KEY, MASK)>;

    /// Put @a content in a popover under @a anchor, closing any other first:
    /// the Lightbox has one popover at a time.
    ALPopover* showPopover(PopoverKind kind, LLView* anchor, LLPanel* content, PopoverKeyHook hook);
    /// Close the popover that is up, keeping what it chose or, escaping,
    /// keeping nothing.
    void closePopover(bool escape);
    /// Told once per popover, as it closes.
    void onPopoverClosed(const LLView* which, bool escaped);

    /// Find a setting or section by name (Ctrl+F): every section and every
    /// setting, ranked against what is typed, and Return goes to it.
    void openFind();
    /// Show a section, or a setting and the section it is in: its tab chosen,
    /// its section opened and scrolled to, and the setting given the keyboard
    /// and its caption lit for a moment. @a target is "s:<section panel>" or
    /// "k:<setting key>", as findCandidates makes them.
    void jumpTo(const std::string& target);
    /// A tab page's label ("Look"), by index.
    std::string pageLabel(size_t page) const;

    void onClickResetControlDefault(const LLSD& userdata);
    void onClickResetSection(const LLSD& userdata);
    /// Set or clear one section's bit in LLPipeline::sGradeBypassMask, from
    /// the checkbox on that section's accordion header. Ticked means the
    /// section is applied, which is the only way a checkbox beside a section
    /// title reads; the bit it drives is a bypass bit, so the sense inverts
    /// here. The settings are never touched, so a comparison cannot dirty
    /// the Look.
    void onToggleSection(LLUICtrl* ctrl, const LLSD& userdata);
    /// Put the number of bypassed grading sections on the Look tab, or take
    /// it off when there are none. A bypass is state nothing else on screen
    /// shows once its section is scrolled away or another tab is up, and it
    /// is easy to forget one is in force while judging the grade.
    void refreshBypassBadge();
    void onCommitVec3(LLUICtrl* ctrl);
    void refreshVec3Row(const std::string& setting_name);
    void setupToneCurve();
    void refreshToneCurve();
    /// Interpret the graph's action (drag, add, remove) against the selected
    /// curve and write that curve's setting: exactly one setting per commit.
    void onCommitToneCurve();
    /// Reset the curve the channel combo selects, and nothing else.
    void onClickResetToneCurveChannel();
    /// Replace the selected curve with a named preset; parameter = preset id.
    void onToneCurvePreset(const LLSD& userdata);
    /// The channel combo's value: -1 for Master, else 0..2 for R, G, B.
    S32  getToneCurveChannel() const;
    void setupSplitToneGraph();
    void refreshSplitToneGraph();
    /// Write balance or one of the two widths, by which handle moved.
    void onCommitSplitToneGraph();
    /// Arm the scene picker; the click that follows sets Temperature and Tint.
    void onClickWhiteBalancePicker();
    void onWhiteBalancePicked(const LLColor3& sample);
    void populateAssetCombo(const std::string& combo_name,
                            const std::string& dir_name,
                            const std::vector<std::string>& extensions,
                            const std::string& setting_name);
    void populateLUTCombo();
    void openUserAssetFolder(const std::string& dir_name);
    /// Open the user's LUT folder in the platform file browser, creating it
    /// first if this is its first use.
    void onClickOpenLUTFolder();
    void onLensDirtSliderHeld(bool held);
    void updateTonemapperRows();
    /// Freeze the frame about to be presented, and switch the wipe on so the
    /// grab is visibly a grab.
    void onClickReferenceGrab();
    /// Drop the still and switch the wipe off.
    void onClickReferenceClear();
    /// Grey the wipe controls while there is nothing to wipe against.
    void refreshReferenceRow();
    /// Grey Undo and Redo to match what the stack can actually do.
    void refreshHistoryButtons();

    // --- Day cycle ---
    //
    // Nothing here pauses a clock, because there is no clock to pause: the
    // cycle position is computed from wall time every frame. Freezing means
    // sampling the running cycle at one position and installing the result as
    // a *fixed* local environment, which is what stops the motion. It is the
    // same move `@setenv_daytime` and the day cycle editor's timeline make.

    /// The day cycle to scrub, from the highest-priority layer that has one.
    /// While frozen, ENV_LOCAL holds a fixed sky and no day at all, so the
    /// cycle has to be read from the parcel or region underneath it -- which
    /// is also what lets scrubbing survive closing and reopening the floater.
    std::shared_ptr<LLSettingsDay> getScrubbableDay() const;
    /// Whether a fixed sky is installed locally. Derived from the world rather
    /// than remembered here, so it stays true when something else changes the
    /// environment behind our back.
    bool isSkyFrozen() const;
    /// Sample the day at `position` and install it as the local environment.
    void applyDayPosition(F32 position);
    /// Remember what we are covering, then freeze.
    void freezeSkyAt(F32 position);
    /// Put back whatever ENV_LOCAL held before the freeze, or clear it.
    void thawSky();
    /// Re-find the landmarks if the underlying day cycle has changed. Blends
    /// ninety-six skies, so it is guarded on the day itself, not called per
    /// frame.
    void refreshDayLandmarks();
    /// Track the world's state and grey what cannot act on it.
    void refreshDayCycleRow();

    void onToggleDayFreeze(LLUICtrl* ctrl);
    void onCommitDayTime(LLUICtrl* ctrl);
    void onClickDayPreset(const LLSD& userdata);
    void onToggleCloudScroll(LLUICtrl* ctrl);
    void onClickRestoreEnvironment();

    /// Record one whitelisted setting moving, unless we are the ones moving it.
    void onGradeSettingChanged(const std::string& name, const LLSD& before, const LLSD& after);
    /// Step the history one transaction and write the values back.
    /// @return false when there was nothing in that direction.
    bool applyHistory(bool redo_direction);

    void onLookSelected();
    void onClickLookSave();
    void onClickLookSaveAs();
    void onClickLookDelete();
    void onClickLookRevert();
    void refreshLooksBar();

    /// The tab strip and its pages, in tab order: Look, Lens, Scene, Sky.
    LLTabContainer* mTabs = nullptr;
    std::vector<LLPanel*> mTabPages;
    /// What popovers hang from.
    LLPanel* mTopBar = nullptr;
    LLHandle<ALPopover> mPopover;
    PopoverKind mPopoverKind = PopoverKind::None;
    /// The caption a jump lit, and how long ago; draw() puts it out.
    LLHandle<LLView> mLitCaption;
    LLFrameTimer mLitTimer;
    /// Every section and setting, found in postBuild. After postBuild nothing
    /// here looks a widget up by name: a page taken out into a window of its
    /// own takes its widgets with it, out of reach of any search from this
    /// floater, and the pointers held here are what keep working.
    ALLightboxDirectory mDirectory;

    /// One per tonemapper parameter row: the operator it belongs to, and the
    /// row's control and reset button, which updateTonemapperRows greys.
    struct TonemapperRow
    {
        S32 mType = 0;
        LLUICtrl* mCtrl = nullptr;
        LLUICtrl* mReset = nullptr;
    };
    std::vector<TonemapperRow> mTonemapperRows;

    // Spinner triplets named "vec3_<Setting>_<0|1|2>", keyed by setting name.
    // Rows are discovered by walking the widget tree in postBuild; adding a
    // vector-valued row is pure XUI.
    /// Any LLUICtrl, not just LLSpinCtrl: the contract is the widget's *name*,
    /// so a slider, a spinner or anything else that carries one number can
    /// stand for a component. Sliders matter for banks of related values --
    /// eight hue sliders read as a shape, eight spinners read as a form.
    std::map<std::string, std::array<LLUICtrl*, 3>> mVec3Rows;
    std::vector<boost::signals2::scoped_connection> mVec3Connections;
    boost::signals2::scoped_connection mTonemapConnection;
    boost::signals2::scoped_connection mLooksListConnection;
    boost::signals2::scoped_connection mLooksActiveConnection;
    LLComboBox* mLooksCombo = nullptr;
    LLUICtrl* mLookSave = nullptr;
    LLUICtrl* mLookDelete = nullptr;
    LLUICtrl* mLookRevert = nullptr;
    bool mVec3Updating = false;

    // Tone curve graph. Optional: the floater builds without it. The four
    // curve settings are read fresh on every refresh and commit rather than
    // mirrored here -- undo, Looks and Debug Settings all write them behind
    // the floater's back.
    std::vector<boost::signals2::scoped_connection> mToneCurveConnections;
    ALCurveEditorCtrl* mToneCurve = nullptr;
    LLComboBox* mToneCurveChannel = nullptr;
    bool mToneCurveUpdating = false;

    // Split-tone band graph. Same contract: optional, and the sliders below it
    // remain the full interface if the XUI drops it.
    std::vector<boost::signals2::scoped_connection> mSplitToneConnections;
    ALCurveEditorCtrl* mSplitToneGraph = nullptr;
    /// The width sliders, whose min_val/max_val are the range the edge
    /// handles clamp into, so the XUI stays the single home of that range.
    LLSliderCtrl* mSplitShadowWidthSlider = nullptr;
    LLSliderCtrl* mSplitHighlightWidthSlider = nullptr;
    bool mSplitToneUpdating = false;

    // Undo. The history is a member, so it lives and dies with the floater:
    // close the Lightbox and the stack is gone. That is the honest scope --
    // the alternative is a stack that outlives the window it belongs to and
    // silently rewrites settings a much later session is editing.
    ALGradeHistory mHistory;
    std::vector<boost::signals2::scoped_connection> mHistoryConnections;
    /// Set while applyHistory writes settings. Those writes fire the same
    /// signals a user edit does, and recording them would append the undo to
    /// the stack it came from.
    bool mApplyingHistory = false;

    // Undo and Redo in the top bar, polled by draw() like the row below:
    // the stack moves on every commit and every Look apply, and hanging a
    // refresh off each of those is more places to forget.
    LLUICtrl* mUndoButton = nullptr;
    LLUICtrl* mRedoButton = nullptr;
    /// Bit 0 can-undo, bit 1 can-redo; -1 until the first refresh.
    S32 mHistoryButtonState = -1;

    // Reference still row. Cached because draw() polls them, and optional
    // because the XUI is free to drop the row.
    LLUICtrl* mReferenceClear = nullptr;
    LLUICtrl* mReferenceMode = nullptr;
    LLUICtrl* mReferencePosition = nullptr;
    /// What the row was last told, so a poll that changes nothing costs
    /// nothing. Tri-state: -1 until the first refresh has run.
    S32 mReferenceRowState = -1;

    // Day cycle row, cached for the same reason and equally optional.
    LLUICtrl* mDayFreeze = nullptr;
    LLUICtrl* mDayTime = nullptr;
    LLUICtrl* mCloudScroll = nullptr;
    LLUICtrl* mRestoreEnvironment = nullptr;
    /// Sunrise, noon, sunset, midnight, in the order the landmarks are named.
    std::array<LLUICtrl*, 4> mDayPresets = {};

    /// Where the slider is. While the sky is running this tracks the live
    /// position, so ticking Freeze holds the moment being looked at rather
    /// than jumping somewhere else first.
    F32 mDayPosition = 0.f;
    /// Landmarks, and the day they were found in. Comparing the day is what
    /// keeps the search off the frame path.
    std::shared_ptr<LLSettingsDay> mLandmarkDay;
    ALDayCycleLandmarks::Landmarks mDayLandmarks;

    /// What ENV_LOCAL held before we froze it. Restoring this is what makes
    /// unticking Freeze an undo instead of a drop to the region default, which
    /// would silently discard a Personal Lighting sky.
    std::shared_ptr<LLSettingsDay> mPreFreezeDay;
    std::shared_ptr<LLSettingsSky> mPreFreezeSky;
    std::shared_ptr<LLSettingsWater> mPreFreezeWater;
    /// Whole seconds: LLSettingsDay::Seconds is S32Seconds, unlike the F64 one
    /// on LLSettingsBase, and holding these as F32 would convert lossily on
    /// the way back in.
    S32 mPreFreezeDayLength = 0;
    S32 mPreFreezeDayOffset = 0;
    /// Whether the fixed sky in place is one we installed. False for a sky the
    /// user set some other way, which we must not claim to be able to undo.
    bool mDayFreezeIsOurs = false;
    /// Bit 0 may change the environment, bit 1 frozen, bit 2 a day to scrub.
    S32 mDayCycleRowState = -1;
};

#endif // AL_FLOATERLIGHTBOX_H
