default {   // state state_body
    state_entry() { // event 
        float i = llFrand(1.0); // to avoid "always true"/"always false" warnings
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)        
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if (i)
        if ( i )
        return;
    }
}

