/**
 * @file lutcube_test.cpp
 * @brief Unit tests for the .cube LUT parser
 *
 * Copyright (c) 2026, Alchemy Viewer Project.
 *
 * The source code in this file is provided to you under the terms of the
 * GNU Lesser General Public License, version 2.1, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. Terms of the LGPL can be found in doc/LGPL-licence.txt
 * in this distribution, or online at http://www.gnu.org/licenses/lgpl-2.1.txt
 *
 * A .cube is untrusted input -- a file the user downloaded and pointed us at.
 * Most of what is below is therefore about what the parser does with a file
 * that is wrong, not one that is right.
 */

#include "linden_common.h"

#include "../test/lltut.h"

#include "../lutcube.h"

#include <sstream>

namespace tut
{
    struct lutcube_data
    {
        /// A well-formed identity cube of side @a n, optionally with @a extra
        /// header lines (DOMAIN_MIN and friends) inserted after the size.
        /// Entries run with red fastest, which is the .cube convention and the
        /// order LutCube advances its cursor in.
        static std::string identity(int n, const std::string& extra = std::string())
        {
            std::ostringstream out;
            out << "# generated by lutcube_test\n";
            out << "TITLE \"identity\"\n";
            out << "LUT_3D_SIZE " << n << "\n";
            if (!extra.empty())
            {
                out << extra << "\n";
            }
            const float last = (float)(n - 1);
            for (int z = 0; z < n; ++z)
            {
                for (int y = 0; y < n; ++y)
                {
                    for (int x = 0; x < n; ++x)
                    {
                        out << (F32)x / last << " " << (F32)y / last << " " << (F32)z / last << "\n";
                    }
                }
            }
            return out.str();
        }

        static LutCube parse(const std::string& text)
        {
            LutCube            cube;
            std::istringstream stream(text);
            cube.parse(stream);
            return cube;
        }

        /// Value at entry @a index of channel @a channel (0 = R, 1 = G, 2 = B).
        /// Entries are 16-bit, so full scale is 65535 and mid grey is 32768.
        static int at(const LutCube& cube, int index, int channel)
        {
            return (int)cube.colorCube[(size_t)index * 4 + channel];
        }

        // constexpr, not const: ensure_equals takes its arguments by reference,
        // which would odr-use a plain static const and want a definition.
        static constexpr int FULL = 65535;
        static constexpr int MID  = 32768;
    };

    typedef test_group<lutcube_data> lutcube_group;
    typedef lutcube_group::object    lutcube_object;
    tut::lutcube_group lcg("LutCube");

    // The ordinary case, and the layout the uploader depends on: red varies
    // fastest, so entry 1 of a size-2 cube is (FULL, 0, 0).
    template<> template<>
    void lutcube_object::test<1>()
    {
        const LutCube cube = parse(identity(2));
        ensure_equals("size", cube.size, 2);
        ensure_equals("entry count", (int)cube.colorCube.size(), 2 * 2 * 2 * 4);

        ensure_equals("black R", at(cube, 0, 0), 0);
        ensure_equals("black G", at(cube, 0, 1), 0);
        ensure_equals("black B", at(cube, 0, 2), 0);

        ensure_equals("red is next R", at(cube, 1, 0), FULL);
        ensure_equals("red is next G", at(cube, 1, 1), 0);
        ensure_equals("red is next B", at(cube, 1, 2), 0);

        ensure_equals("white is last R", at(cube, 7, 0), FULL);
        ensure_equals("white is last G", at(cube, 7, 1), FULL);
        ensure_equals("white is last B", at(cube, 7, 2), FULL);
    }

    // Quantisation rounds rather than truncates. 0.5 * 65535 is 32767.5;
    // truncating biases every entry in the cube downwards by up to one step,
    // which on an identity LUT is a darkening for no reason at all.
    template<> template<>
    void lutcube_object::test<2>()
    {
        const LutCube cube = parse(identity(3));
        ensure_equals("size", cube.size, 3);
        // Entry 1 is x = 1 of 2, i.e. exactly mid grey on red alone.
        ensure_equals("mid rounds up", at(cube, 1, 0), MID);
    }

    // DOMAIN_MIN was parsed and then ignored: the original divided by the span
    // but never subtracted the offset. With a domain of [-1, 1], an input of 0
    // is the middle of the domain and must land on mid grey -- the old code put
    // it at 0.
    template<> template<>
    void lutcube_object::test<3>()
    {
        std::ostringstream text;
        text << "LUT_3D_SIZE 2\n";
        text << "DOMAIN_MIN -1.0 -1.0 -1.0\n";
        text << "DOMAIN_MAX 1.0 1.0 1.0\n";
        for (int i = 0; i < 8; ++i)
        {
            text << "0.0 0.0 0.0\n";
        }

        const LutCube cube = parse(text.str());
        ensure_equals("size", cube.size, 2);
        ensure_equals("domain centre is mid grey", at(cube, 0, 0), MID);
        ensure_equals("domain centre is mid grey", at(cube, 0, 1), MID);
        ensure_equals("domain centre is mid grey", at(cube, 0, 2), MID);
    }

    // The one that shows up as an artefact rather than a failure. "clampTripel"
    // did not clamp, so 1.1 became 255 * 1.1 = 280, which wrapped to 24 on the
    // cast -- a blown highlight rendered as near-black speckle. Below the
    // domain wrapped the other way.
    template<> template<>
    void lutcube_object::test<4>()
    {
        std::ostringstream text;
        text << "LUT_3D_SIZE 2\n";
        for (int i = 0; i < 8; ++i)
        {
            text << "1.1 -0.4 0.5\n";
        }

        const LutCube cube = parse(text.str());
        ensure_equals("above domain clamps to white", at(cube, 0, 0), FULL);
        ensure_equals("below domain clamps to black", at(cube, 0, 1), 0);
        ensure_equals("in domain is untouched", at(cube, 0, 2), MID);
    }

    // Legal .cube files indent their data, and the original required a digit at
    // column zero. A rejected row does not merely lose itself: every later row
    // slides up into its slot, so the whole cube is wrong and the tail is left
    // at the full-scale fill. Indented, signed and bare-decimal rows all count.
    template<> template<>
    void lutcube_object::test<5>()
    {
        const LutCube plain = parse(identity(2));

        std::ostringstream text;
        text << "LUT_3D_SIZE 2\n";
        text << "    0.0 0.0 0.0\n";     // leading spaces
        text << "\t+1.0 0.0 0.0\n";      // tab, and an explicit plus
        text << "  .0 1.0 0.0\n";        // bare decimal point
        text << "1.0 1.0 0.0\n";
        text << "0.0 0.0 1.0\n";
        text << "1.0 0.0 1.0\n";
        text << "0.0 1.0 1.0\n";
        text << "1.0 1.0 1.0\n";

        const LutCube indented = parse(text.str());
        ensure_equals("indented cube is accepted", indented.size, 2);
        ensure("indented cube matches the plain one", indented.colorCube == plain.colorCube);
    }

    // The memory-safety one. With no LUT_3D_SIZE the cube is never allocated and
    // size stays zero, and the original wrote the first data row into it
    // regardless. Rejecting the file is the whole fix; the assertion here is
    // that we get an empty cube back and not a crash.
    template<> template<>
    void lutcube_object::test<6>()
    {
        const LutCube cube = parse("0.0 0.0 0.0\n1.0 1.0 1.0\n");
        ensure("data before LUT_3D_SIZE is rejected", cube.colorCube.empty());
        ensure_equals("and leaves no size", cube.size, 0);
    }

    // A short file used to be kept. The allocation is prefilled with full
    // scale, so everything past the last row read came out white -- an "almost
    // working" LUT that blows out the top of the image.
    template<> template<>
    void lutcube_object::test<7>()
    {
        std::string text = identity(2);
        text.erase(text.find_last_of('\n', text.size() - 2) + 1);

        const LutCube cube = parse(text);
        ensure("an incomplete cube is rejected", cube.colorCube.empty());
    }

    // stof/stoi throw, and nothing used to catch them, so a corrupt file threw
    // out of setupGradingLUT rather than falling back.
    template<> template<>
    void lutcube_object::test<8>()
    {
        const LutCube bad_size = parse("LUT_3D_SIZE banana\n");
        ensure("a non-numeric size is rejected", bad_size.colorCube.empty());

        std::ostringstream text;
        text << "LUT_3D_SIZE 2\n";
        text << "0.0 0.0 0.0\n";
        text << "0.5 what 0.5\n";
        const LutCube bad_row = parse(text.str());
        ensure("a malformed row is rejected", bad_row.colorCube.empty());
    }

    // An absurd size should be refused before it is allocated, not after.
    template<> template<>
    void lutcube_object::test<9>()
    {
        ensure("a huge size is rejected", parse("LUT_3D_SIZE 100000\n").colorCube.empty());
        ensure("a degenerate size is rejected", parse("LUT_3D_SIZE 1\n").colorCube.empty());
        ensure("a negative size is rejected", parse("LUT_3D_SIZE -4\n").colorCube.empty());
    }

    // Values separated by runs of spaces or by tabs, and a file with CRLF line
    // endings read somewhere that does not strip the CR. The original split on
    // the first " \n" it found and lost a value to any of these.
    template<> template<>
    void lutcube_object::test<10>()
    {
        const LutCube plain = parse(identity(2));

        std::ostringstream text;
        text << "LUT_3D_SIZE 2\r\n";
        text << "0.0\t0.0\t0.0\r\n";
        text << "1.0   0.0   0.0\r\n";
        text << "0.0 1.0 0.0\r\n";
        text << "1.0 1.0 0.0\r\n";
        text << "0.0 0.0 1.0\r\n";
        text << "1.0 0.0 1.0\r\n";
        text << "0.0 1.0 1.0\r\n";
        text << "1.0 1.0 1.0\r\n";

        const LutCube odd = parse(text.str());
        ensure_equals("odd whitespace is accepted", odd.size, 2);
        ensure("odd whitespace matches the plain cube", odd.colorCube == plain.colorCube);
    }

    // A value the text can carry but the arithmetic cannot survive. Whether a
    // stream accepts "nan" or "inf" as a float varies by standard library, so
    // the parser must reject them itself rather than lean on the extraction
    // failing: a NaN sails through llclamp (both comparisons are false) and
    // the cast to unsigned short is undefined behaviour.
    template<> template<>
    void lutcube_object::test<11>()
    {
        static const char* const poison[] = { "nan", "inf", "-inf" };
        for (const char* value : poison)
        {
            std::ostringstream text;
            text << "LUT_3D_SIZE 2\n";
            text << "1.0 " << value << " 0.5\n";
            for (int i = 0; i < 7; ++i)
            {
                text << "0.0 0.0 0.0\n";
            }
            ensure(std::string("a ") + value + " value is rejected",
                   parse(text.str()).colorCube.empty());
        }

        // The domain lines go through the same reader, and a non-finite domain
        // poisons the quantisation of every row instead of just one.
        std::ostringstream domain;
        domain << "LUT_3D_SIZE 2\n";
        domain << "DOMAIN_MAX inf inf inf\n";
        for (int i = 0; i < 8; ++i)
        {
            domain << "0.0 0.0 0.0\n";
        }
        ensure("a non-finite domain is rejected", parse(domain.str()).colorCube.empty());
    }
}
